### ISSUE TITLE
Fix or replace AppVeyor bottleneck

### ISSUE THREAD

**Issue by Gabriel439** [dhall-lang/dhall-haskell#1063]
Right now AppVeyor is severely limiting the rate at which we can merge pull requests because each revision it builds takes ~30 minutes and it can only build one revision at a time.

One possible solution is to replace AppVeyor with Azure DevOps since the latter supports up to 10 concurrent builds free for open source projects

**Comment by jneira** [comment]
@Gabriel439 i am afraid that azure still doesn't support caching between builds so each one would take longer.
They are going to add support soon, though.

**Comment by EggBaconAndSpam** [comment]
AppVeyor doesn't seem to be doing any caching either... It's downloading everything again for each build. Switching to azure is probably not going to make things worse ;)

**Comment by ocharles** [comment]
What is AppVeyor used for?

**Comment by jneira** [comment]
@EggBaconAndSpam withouth caching it takes 40+ mins instead 15+!
@ocharles to make build+test+artifacts for windows

**Comment by jneira** [comment]
But i agree in change the ci to azure, you have unlimited build time and you can build using linux, mac and windows.
Recently hie started to use it succesfully.

**Comment by ocharles** [comment]
>  @ocharles to make build+test+artifacts for windows

Could this now be done using [haskell.nix](https://github.com/input-output-hk/haskell.nix) cross compilation to Windows on Hydra?

**Comment by joneshf** [comment]
Whoa, Nice!

**Comment by Gabriel439** [comment]
@ocharles: I took a look at that a while back.  The main issue was that the Windows cross-compilation support doesn't appear work with the static Haskell executables work from https://github.com/NixOS/nixpkgs/issues/43795 (which is Linux-specific)

**Comment by sjakobi** [comment]
Currently AppVeyor takes ~35 to 45 minutes per build. I believe much of that time is spent on re-building dependencies that I wish would be cached. I've tried to look around for projects with a working cache setup, but I couldn't find one. :(

**Comment by joneshf** [comment]
The [appveyor builds for `purty`][appveyor] tend to hit the cache and run in 2-5 minutes. It's using `dhall` and `purescript` as dependencies, though a fairly small project overall. The [`appveyor.yml`][] shows the caching: [`STACK_ROOT`][] is wherever Appveyor puts it and the key is [relative][]. That looks like the only stuff that's different. Could that be it?

It doesn't look like the `dhall-haskell` builds are even trying to cache things at the end. For reference, at the very end of the build, [the cache is updated][update] for `purty`. Is it possible there's something you have to turn on in the settings? It's been a long time since I set this up, so I don't remember all the steps I went through. More than happy to provide whatever help I can though, so let me know if there's anything else I can do.

[`appveyor.yml`]: https://gitlab.com/joneshf/purty/blob/3c073e1149ecdddd01f1d371c70d5b243d743bf2/appveyor.yml
[`stack_root`]: https://gitlab.com/joneshf/purty/blob/3c073e1149ecdddd01f1d371c70d5b243d743bf2/appveyor.yml#L30
[appveyor]: https://ci.appveyor.com/project/joneshf/purty/history
[relative]: https://gitlab.com/joneshf/purty/blob/3c073e1149ecdddd01f1d371c70d5b243d743bf2/appveyor.yml#L10
[update]: https://ci.appveyor.com/project/joneshf/purty/builds/26168720#L21046

**Comment by sjakobi** [comment]
Thanks for the help @joneshf! I'll try to copy a few things from `purty` then! :)

> It doesn't look like the `dhall-haskell` builds are even trying to cache things at the end. For reference, at the very end of the build, [the cache is updated](https://ci.appveyor.com/project/joneshf/purty/builds/26168720#L21046) for `purty`.

It seems to me that updating the cache may be limited to builds on `master`: [This build](https://ci.appveyor.com/project/Gabriel439/dhall-haskell/builds/26494623/job/p58tdm92x1aqm28q?fullLog=true#L2613) does it, but [that one](https://ci.appveyor.com/project/Gabriel439/dhall-haskell/builds/26493370/job/roe0hmacgv81t8px?fullLog=true) doesn't.

**Comment by sjakobi** [comment]
After #1207 and #1214 [AppVeyor builds](https://ci.appveyor.com/project/Gabriel439/dhall-haskell/history) typically take 10-11 minutes now.

The main problem seems to have been that we got the syntax for the cache rules wrong!

**Comment by Gabriel439** [comment]
*shakes fist at YAML*
