### ISSUE TITLE
Split up the Dhall.Core module

### ISSUE THREAD

**Issue by sjakobi** [dhall-lang/dhall-haskell#1127]
It has become a bit annoying to work on `Dhall.Core` because it takes so long to recompile! I suspect that this is mostly due to the many instances derived and defined in it. AFAIK GHC also takes longer to compile a large module than many small ones.

My main idea is to separate the normalization code (except `denote`) from the type and instance declarations. This could happen either by moving the normalization stuff to a new module (`Dhall.Normalization`?) or by moving the types to a new module (`Dhall.Expr`?). Both ways should allow us to delete the `Dhall.Eval` `.hs-boot` file.

**Comment by MonoidMusician** [comment]
If you're looking for ideas, I did split up [`Dhall.Core`](https://github.com/MonoidMusician/dhall-purescript/blob/master/src/Dhall/Core.purs) into many files in my PS implementation (WIP; I don't claim it's pretty code yet!). Essentially what I did was:
- one module for the AST, broken up into various sub-modules (for the basic types, the main AST type and instances, another operations on it, and another one for constructors because the way I did it in PS is verbose abstract nonsense …): https://github.com/MonoidMusician/dhall-purescript/blob/master/src/Dhall/Core/AST.purs
- another module for the common operations on variables (like `shift`, `subst`, etc.): https://github.com/MonoidMusician/dhall-purescript/blob/master/src/Dhall/Variables.purs
- one big one for normalizing: https://github.com/MonoidMusician/dhall-purescript/blob/master/src/Dhall/Normalize.purs
- and another one for imports: https://github.com/MonoidMusician/dhall-purescript/blob/master/src/Dhall/Core/Imports/Types.purs (I currently just have the types, I need to actually implement the algorithms)

It's all abstract nonsense and doesn't quite correspond to the Haskell anymore, but maybe the overall organization could be useful.

**Comment by Gabriel439** [comment]
@sjakobi: Yeah, I think splitting it up is fine.  My only recommendation is to still keep the public API of `Dhall.Core` the same to avoid disruption to downstream users (i.e. split it into other modules which it just re-exports).

**Comment by sjakobi** [comment]
Actually @AndrasKovacs announced in https://github.com/dhall-lang/dhall-haskell/issues/1129#issue-469678029 that his NbE work would include refactoring the module layout. So I'll wait to see how things develop with the NbE work before revisiting this issue again.

**Comment by sjakobi** [comment]
See #1440 for step 1 of splitting `Dhall.Core`. In step 2 I want to move the normalization logic into a new module `Dhall.Normalize`
