### ISSUE TITLE
Tests cannot be ran without an active network connection

### ISSUE THREAD

**Issue by ocharles** [dhall-lang/dhall-haskell#1135]
For example, when trying to install Dhall with the Nix sandbox enabled:

```
      ./dhall-lang/tests/import/success/headerForwardingA.dhall:                                FAIL
        Exception: 
        ↳ https://test.dhall-lang.org/Bool/package.dhall using [ { mapKey = "Test", mapValue = "Example" } ]
        
        Error: Remote host not found
        
        
        15│ https://test.dhall-lang.org/Bool/package.dhall
        16│   using [ { mapKey = "Test", mapValue = "Example" } ]
        
        15:1
```

I suggest we spin up a local HTTP server for these tests.

**Comment by Gabriel439** [comment]
@ocharles: How would we get the tests to use to that server?

**Comment by ocharles** [comment]
One option is to rewrite all the tests to access `localhost` instead and document how test harnesses should setup a local server.

**Comment by Gabriel439** [comment]
@ocharles: The main issue is that this greatly increases the test burden of implementation authors, especially the parts of the test that require CORS support or two domains, one of which is protected by authenticated headers

**Comment by ocharles** [comment]
I suppose the other option is that `dhall-haskell` could be more configurable in terms of how it does HTTP, and we could just mock the responses out rather than even bothering with a server. Then when we run tests, we can implement a pure approach

**Comment by ocharles** [comment]
Thanks for the response. I think there may be a solution here to fix this, but we don't need to keep the issue around. But if someone wants to propose a fix in a PR (e.g., me) - great!

**Comment by ocharles** [comment]
Also, it looks like #1159 should have fixed this anyway, if I understand correctly.

**Comment by EggBaconAndSpam** [comment]
> Also, it looks like #1159 should have fixed this anyway, if I understand correctly.


Yes! I forgot to mention that here...

**Comment by Anton-Latukha** [comment]
I would bump this.

Accepting the https://github.com/dhall-lang/dhall-haskell/issues/1135#issuecomment-513241959 greatly.

But since thread gives further hints of resolving this.

Is this can be resolved now?

Nixpkgs escapes testing the package in its ecosystem because of _*this_ issue, since Nix builds by default do not permit the network use.

---

Maybe it is possible the other way around, to permit Nixpkgs build to access to network. I remeber reading/participating in such discussions, but IDK or forgot does allowing network to the test in Nixpkgs is possible. AFAIK that is possible only with overloading Nix configuration, turned off sandboxing. Which in turn is AFAIK not allowed/possible in Nixpkgs.

---

The pass of least resistance and easy way - is to separate networking tests into a separate test group.

That would allow the normal testing in Nixpkgs, then Nixpkgs builds can use the default or overloaded test group that excludes network tests.
The bonus that the DHall nix project would get - integration testing of it in Nixpkgs, which would also define DHall in Nix ecosystem would work properly, and also would enable a better self-maintenance of the package in Nixpkgs by the community.
