### ISSUE TITLE
Confusing repl session when you introduce Kinds

### ISSUE THREAD

**Issue by ocharles** [dhall-lang/dhall-haskell#1193]
```
$ dhall repl
⊢ <A : Kind>

< A : Kind >

⊢ :t True

Error: ❰Sort❱ has no type, kind, or sort
```

**Comment by sjakobi** [comment]
@Gabriel439 has explained this to me before, but I forgot about it: https://github.com/dhall-lang/dhall-haskell/issues/1020#issuecomment-506080597

Maybe we can avoid inferring the type of everything?

**Comment by Gabriel439** [comment]
The behavior was changed since then to desugar previous bindings to `let` expressions, so the REPL session is equivalent to this:

```
$ dhall <<< 'let it = < A : Kind > in True' 
Use "dhall --explain" for detailed errors

Error: ❰Sort❱ has no type, kind, or sort

1│ let it = < A : Kind > in True

(stdin):1:1
```

... so the real question is why that expression does not type-check.

Looking at the code, it appears this is due to the code inferring the type of the right-hand side of the binding twice in a row:

https://github.com/dhall-lang/dhall-haskell/blob/3abef4e3f0bb787fe3263349245baf19ad1fdba4/dhall/src/Dhall/TypeCheck.hs#L153-L165

In particular the last line (inferring the type of `_A1`) is what is causing this error, and the only reason it is there it is used for a pre-dependent-types fast path, which goes away once the dependent types branch is merged.

Indeed, on the dependent types branch the problem disappears:

```
$ dhall <<< 'let it = < A : Kind > in True'
True
```
