### ISSUE TITLE
`yaml-to-dhall 'Natural' <<<3.0` does not fail

### ISSUE THREAD

**Issue by vvv** [dhall-lang/dhall-haskell#1241]
This command rightfully fails:
```
$ yaml-to-dhall 'Natural' <<<3.1415


Error: Dhall type expression and json value do not match:

Dhall:
Natural

YAML:
3.1415
```

But this one succeeds:
```
$ yaml-to-dhall 'Natural' <<<3.0
3
```

I'm not sure if this is a bug...  Definitely a curiosity, which I wanted to share. :)

**Comment by sjakobi** [comment]
This is due to our use of `aeson`'s `Value` to represent YAML. `Value` was made to represent `JSON` and represents all numbers as floating point numbers.

The conversion happens here:

https://github.com/dhall-lang/dhall-haskell/blob/96c94ddfc4ac0d7972a1972770f0153255537e16/dhall-json/src/Dhall/JSONToDhall.hs#L481-L487

https://github.com/dhall-lang/dhall-haskell/issues/744 would fix this.

**Comment by vvv** [comment]
Thanks for clarification, @sjakobi!
