### ISSUE TITLE
Strange diff involving lists

### ISSUE THREAD

**Issue by sjakobi** [dhall-lang/dhall-haskell#1243]
```
$ dhall diff 'True' '[1]'
- True
+ [ … ] : …
```

I would have expected the last line to be

```
+ [ 1 ]
```

Possibly related to https://github.com/dhall-lang/dhall-haskell/issues/1211!?

**Comment by Gabriel439** [comment]
@sjakobi: The diff only includes displays the minimum difference (i.e. the skeleton) when comparing two expressions like that.  In this case, the diff doesn't even have to display the contents of the list because just the fact that it is a list is enough to discern that they differ.  That's why it displays `[ … ]`

However, we could slightly simplify it by not displaying the `: …` if the list is non-empty.

**Comment by Gabriel439** [comment]
I forgot to mention another reason why the diff only displays the skeleton: the contents of the list might be large.  For example, if the first element of the list were a large expression we would not want to render that expression.

**Comment by sjakobi** [comment]
Oh, that makes sense! Thanks!

**Comment by ocharles** [comment]
>  For example, if the first element of the list were a large expression we would not want to render that expression.

We would not want to render *all* of that expression, I do think a little more context would be useful though. It could be just the first "level" of the adjacent children, without recursing into their children. This is like how `diff` shows me the three leading and trailing lines per hunk.
