### ISSUE TITLE
Avoid depending on free and distributive

### ISSUE THREAD

**Issue by vmchale** [dhall-lang/dhall-haskell#1297]
Unfortunately, `free` and `distributive` (and all that depend on them) break cross-compilation via `cabal-install` due to https://github.com/ekmett/distributive/pull/53#issuecomment-529462676

Would it be possible to avoid depending on them? They introduce a large dependency footprint. 

This would entail (directly) not depending on `free`, `either`, and `recursion-schemes`.

**Comment by sjakobi** [comment]
@vmchale Note that `dhall` [plans on using `cabal-doctest`](https://github.com/dhall-lang/dhall-haskell/pull/1125) too!

Regarding the dependencies: In principle we could put them behind feature-flags.

**Comment by Gabriel439** [comment]
@vmchale: Do you have any issue with a dependency on the `data-fix` package?

**Comment by vmchale** [comment]
@sjakobi Oh hmm. I'll comment over there. This is ostensibly a `cabal-install` problem but I'm guessing it will take a lot of work to fix. 

@Gabriel439 nope. Nothing wrong with recursion schemes :)

**Comment by quasicomputational** [comment]
`cabal-install` bugs aside, this issue would also be fixed by Cabal learning how to drive `doctest` properly. It's a very worthy long-term goal, but it's non-trivial. For the time being I am quite definitely -1 on excising `cabal-doctest` because it really is carrying weight - plumbing the correct dependency information around without it is somewhere between very hard and actively impossible to maintain.

Also, on removing `distributive`, that entails no `profunctor`, which would mean no prisms or isos (or, at least, none that will interoperate with the rest of the Kmettverse). Not that there are currently any of those at present, but foreclosing the possibility is another thing weighing against this in my mind.

**Comment by Gabriel439** [comment]
I think the thing I can definitely do is remove the dependency on `free` and `recursion-schemes`.  Those dependencies are very easy to excise and I'll have a pull request ready soon.  I've actually been meaning to do that anyway and this gives me an excuse to do so.

Removing other dependencies will be trickier and I'd like to first explore other alternatives

**Comment by Gabriel439** [comment]
The fix to remove the `free`/`recursion-schemes` dependencies is up here: https://github.com/dhall-lang/dhall-haskell/pull/1298

**Comment by Gabriel439** [comment]
This was fixed by #1298
