### ISSUE TITLE
`freeIn` incorrectly relies on Expr's Eq instance

### ISSUE THREAD

**Issue by sjakobi** [dhall-lang/dhall-haskell#1341]
This should be `False`:

```
λ> V "x" 0 `freeIn` DoubleLit (0/0)
True
```

https://github.com/dhall-lang/dhall-haskell/blob/08747af8d30a9bcf11490076cdfc8eeca0e6c305/dhall/src/Dhall/Core.hs#L2067-L2075

**Comment by sjakobi** [comment]
Not sure about the best fix. One option would be to compare the encoded bytestrings.

**Comment by AndrasKovacs** [comment]
For `freeIn`, a recursive function on `Expr` seems best to me.

**Comment by sjakobi** [comment]
> For `freeIn`, a recursive function on `Expr` seems best to me.

That would certainly be the most efficient solution.

BTW, do you happen to have an idea how `freeIn` could be implemented for `Val`? That could be useful for type-checking `merge`: https://github.com/dhall-lang/dhall-haskell/pull/1337#discussion_r327283326

**Comment by AndrasKovacs** [comment]
> Or we could use `judgmentallyEqual`.

`Eval.conv` should be a bit more efficient, if we don't want to write out the big recursive function, and we also have access to a value `Environment`. Then, instead of using `subst`, we can add a definition to a bound var in the environment, and then evaluate. 

> BTW, do you happen to have an idea how freeIn could be implemented for Val?

IIRC it's a straightforward recursion on `Val`, and we go under binders the exact same way as in `Eval.conv`, by getting fresh vars and instantiating closures with them.
