### ISSUE TITLE
Update the list of language integrations on dhall-lang.org?

### ISSUE THREAD

**Issue by sjakobi** [dhall-lang/dhall-haskell#1444]
Are dhall-rust and dhall-golang ready to be included there, @Nadrieril, @philandstuff?

What about dhall-purescript @MonoidMusician?

Should dhall-xml be listed too @singpolyma?

**Comment by Nadrieril** [comment]
dhall-rust is mostly usable, but tremendously lacks polish. I want to soften the edges a bit more before I make it public

**Comment by sjakobi** [comment]
Don't let the perfect be the enemy of the good, @Nadrieril! ;)

**Comment by singpolyma** [comment]
Yeah, `dhall-to-xml` and `xml-to-dhall` should be fully usable

**Comment by philandstuff** [comment]
Not much has changed since [this discourse thread](https://discourse.dhall-lang.org/t/state-of-dhall-golang/77). In particular, I want better unmarshalling support (ie the ability to decode dhall directly into Go structs) before an official 1.0 release.

**Comment by sjakobi** [comment]
I wonder what the bar is for an integration to be listed there. I don't mean to criticize dhall-clj, but it's advertised as being "quite alpha", doesn't support HTTP imports, and hasn't been updated since April…

**Comment by Gabriel439** [comment]
@sjakobi: I try not to push people to announce prematurely.  I've been burned on some of my own prior open source projects by prematurely releasing them, which increased my stress until I got them into a low-maintenance state.  Announcing implies a level of commitment from the maintainer(s) that shouldn't be rushed into, especially if they have any quality concerns

For example: one thing that can really increase stress is receiving an "existential" bug report that indicates that some design decision was incorrect and the package needs to be fundamentally rewritten (at a time when one is not prepared to do so)

Regarding your latter question about the level of completion for an integration to be listed: it basically comes down to whether or not the maintainer feels comfortable announcing (and therefore committing to supporting) the package and its fitness for use as a Dhall integration

**Comment by sjakobi** [comment]
Makes sense. Sorry for being pushy!

**Comment by Gabriel439** [comment]
@sjakobi: No worries! 🙂

**Comment by jiegillet** [comment]
Somewhat related, I've been working on a `toml-to-dhall` using the `tomland` package that I'm familiar with. It's still very WIP at the moment, but is that something you'd be interested in adding here?

**Comment by sjakobi** [comment]
That sounds great @jiegillet! :)

**Comment by Gabriel439** [comment]
@jiegillet: Yeah, we would definitely accept adding a `dhall-toml` package to this repository

**Comment by f-f** [comment]
@sjakobi: thanks for bringing this up! I've been meaning to clarify the status of dhall-clj at some point, and this definitely feels the right moment to do it:
- as Gabriel noted, I don't think there should be a specific bar other than the willingness of authors to announce things
- in the case of dhall-clj I did feel comfortable announcing it at the time because only HTTP imports were missing
- I still feel comfortable recommending it to Clojure people and as far as I know it doesn't have too many embarrassing bugs (I.e. I had some reports of people using it)
- Last commit there is April because that was the time where the Go and Rust integrations were picking up steam, and *a lot* of changes went in then. I decided to quiesce the development until the rate of changes to the standard would slow down, which is the case in the last months
- however since then I decided to rewrite the thing in Java (for maintainability reasons), and that's happening right now
- this said, I'd be fine with dropping dhall-clj from the list of integrations if we don't feel comfortable with recommending it to people in general

**Comment by jneira** [comment]
> however since then I decided to rewrite the thing in Java (for maintainability reasons), and that's happening right now

@f_f when i implemented the dhall-eta thing[ i separated the POJOs representing the dhall ast and other data types like errors](https://github.com/eta-lang/dhall-eta/tree/master/java) from the code that uses it, have you plan to do something similar? It would be great to have a common base lib for all jvm implementations (but it had not to be the `dhall-eta` one of course)

**Comment by sjakobi** [comment]
Is there a good logo that we could use for the `dhall-xml` entry? [This one](https://de.wikipedia.org/wiki/Datei:Xml_logo.svg) isn't great, but it's free…

**Comment by Gabriel439** [comment]
@sjakobi: Yeah, that seems fine.  The logos don't have to look pretty

**Comment by sjakobi** [comment]
I have added the XML integration in https://github.com/dhall-lang/dhall-haskell/pull/1481.

Thanks for the status updates everyone! :)

**Comment by f-f** [comment]
@jneira yes! I looked at `dhall-eta` and liked the approach, as it seems sensible to separate "data classes" from the rest (and eventually publish them as a separate library). I'll look more into this once I get to a more working state with this thing 🙂
