### ISSUE TITLE
`dhall format` removes double quotes from POSIX env-vars

### ISSUE THREAD

**Issue by sjakobi** [dhall-lang/dhall-haskell#1468]
```
$ echo 'env:"1"' | dhall format
env:1
$ echo 'env:"1"' | dhall format | dhall format
env : 1
```

```
$ echo 'env:"."' | dhall format
env:.
$ echo 'env:"."' | dhall format | dhall format
dhall: 
Error: Invalid input

(stdin):1:6:
  |
1 | env:.
  |      ^
unexpected newline
expecting expression or whitespace
```

There might be potential for another property test here: Check that the result of formatting and parsing an expression twice still parses.

**Comment by sjakobi** [comment]
I think the proper way to fix this is to distinguish between bash env-vars and POSIX env-vars in the AST, i.e. add a sum-type to distinguish between the two:

https://github.com/dhall-lang/dhall-haskell/blob/16e6a12c3da1966b095cc8089d8c1274c8fca4e5/dhall/src/Dhall/Syntax.hs#L939-L945

Here is the parser that would need to be updated:

https://github.com/dhall-lang/dhall-haskell/blob/16e6a12c3da1966b095cc8089d8c1274c8fca4e5/dhall/src/Dhall/Parser/Expression.hs#L750-L767

**Comment by sjakobi** [comment]
I wonder whether `dhall format` should continue to remove quotes on env-vars that are valid bash env-vars.

**Comment by Gabriel439** [comment]
@sjakobi: As a general rule of thumb, the Haskell AST should match the binary encoding.  So, in other words, if the binary encoding does not distinguish between two representations then neither should the Haskell AST.  Vice versa, if the binary encoding does distinguish between two representations then so should the Haskell AST.  You can think of the official binary encoding as a language-independent AST that is unambiguous, so the more closely the implementation AST mirrors the encoding the more accurately it follows the standard.

So in the case of Bash vs. Posix environment variables, the binary encoding does not distinguish them, so neither should the Haskell AST.  Also, the bugs you are seeing can be fixed without adding an AST distinction between the two.

In both cases the bugs can be fixed by updating the pretty-printing logic for `ImportType` to correctly quote the environment variable when the name contains special characters.  This is similar to how we don't distinguish quoted vs unquoted labels in the Haskell AST and we only quote them when formatting if they have special characters.
