### ISSUE TITLE
Should "dhall freeze" refreeze imports?

### ISSUE THREAD

**Issue by amarrella** [dhall-lang/dhall-haskell#1470]
Hi, it looks like that when I run `dhall freeze --inplace` on files with imports that have already been frozen the hashes are not recomputed. Sometimes I update the tag of my imports and I forget to delete the sha, leading to surprising behaviour because i have the old hash still in my cache.

Is this a security feature or should `dhall freeze` effectively recompute the hashes? If that's not the desired default, would it be possible to add a flag to force refreezing?

CC @barambani

**Comment by Gabriel439** [comment]
@amarrella: It looks like my memory was wrong: I only implemented support for refreezing a semantic integrity check if import resolution failed.  In this case, that didn't fix the hash because import resolution succeeded (due to a cache hit based on the hash).  This is because according to the standard `dhall` prioritizes the hash address over the path as the "true" import when they disagree.

However, the standard doesn't say anything about how `dhall freeze` should behave and I agree that it makes more sense for it to ignore the cache for the purposes of re-freezing imports.  This is also a pretty easy fix.

**Comment by Gabriel439** [comment]
Fix is up here: https://github.com/dhall-lang/dhall-haskell/pull/1471

**Comment by amarrella** [comment]
That's great :) Thanks @Gabriel439!

**Comment by Gabriel439** [comment]
@amarrella: You're welcome! 🙂
