### ISSUE TITLE
Formatting: put parentheses around (./foo as X)?

### ISSUE THREAD

**Issue by neongreen** [dhall-lang/dhall-haskell#1504]
Currently `f (./foo as X)` is formatted as `f ./foo as X`.

I keep mentally parsing it as `(f ./foo) as X`, for two reasons:

* "function application binds tighter than (almost) anything, right?"

* "even if not, `as` is an operator and so it's gotta /definitely/ bind less tight than function application, right?"

Depending on how widespread this confusion is (please chime in!), we might want to alleviate it in `dhall format` with explicit parentheses: `f (./foo as X)`.

**Comment by Gabriel439** [comment]
@neongreen: My preference is to upstream precedence changes into the standard grammar if the current precedence rules are confusing, rather than changing the formatter.  The main reasons are:

* Not everybody uses the formatter
* Other Dhall implementations need to pretty-print expressions, too, and upstreaming the desired precedence into the standard means they are more likely to parenthesize things in the same way as the Haskell implementation

**Comment by neongreen** [comment]
It would break a lot of existing code, though. But sure, I can make a proposal at dhall-lang/dhall-lang. How would the deprecation process look like?

**Comment by Gabriel439** [comment]
@neongreen: The deprecation process would be for `dhall lint` to parenthesize it the way you suggested for a few releases, then we merge the breaking change to the standard (plus document this all in the wiki like we do for other migrations)

**Comment by sjakobi** [comment]
@neongreen, since the discussion has moved to https://github.com/dhall-lang/dhall-lang/issues/834, can this issue be closed?
