### ISSUE TITLE
Cache can get into a weird state

### ISSUE THREAD

**Issue by akshaymankar** [dhall-lang/dhall-haskell#1540]
We came across this error:
```
dhall:
↳ ./pipelines/dhall-modules/test-and-build-docker-images.dhall
  ↳ ./pipelines/dhall-modules/jobs/create-secret-smuggler-docker-image.dhall
DeserialiseFailure 0 "end of input"

4│     ./jobs/create-secret-smuggler-docker-image.dhall

/Users/i336730/go/src/code.cloudfoundry.org/eirini-ci/pipelines/dhall-modules/test-and-build-docker-images.dhall:4:5
```

`./pipelines/dhall-modules/jobs/create-secret-smuggler-docker-image.dhall` is not even a protected import. But when we cleared the cache, the error went away. Hence we think it is due to cache getting in a weird state.

Best,
Akshay && @gdankov

**Comment by Gabriel439** [comment]
@akshaymankar: The Haskell implementation automatically uses an additional cache for local file imports (known as a "semi-semantic" cache), to transparently accelerate things.  You can find that cache in `~/.cache/dhall-haskell`.  Did you happen to also delete that cache when debugging this?

**Comment by akshaymankar** [comment]
We deleted both `~/.cache/dhall` and `~/.cache/dhall-haskell` at once.

**Comment by Gabriel439** [comment]
@akshaymankar: Then it seems likely that this was due to `~/.cache/dhall-haskell` having a malformed binary expression inside of it.

The next time this happens the thing you can do to help us debug is to attach the file output by the following command:

```bash
$ echo "~/.cache/dhall-haskell/1220$(dhall resolve --file ./failed/import.dhall | dhall hash | sed 's/sha256://')"
```

**Comment by akshaymankar** [comment]
Cool, I will keep this in mind. Hopefully if someone else hits this error, internets will lead them here before they delete cache :)

**Comment by trskop** [comment]
We encountered this problem as well on one of our build agents today.  We were able to reconstruct the scenario as follows:

1. Build agent ran out of disk space.
2. In parallel `dhall-to-json` was executed, which produced invalid files in `~/.cache/dhall-haskell/` directory.
3. Build failed and agent got recycled, i.e. workspace, temporary files, and build artefacts were removed.
4. Next time the same build agent was picked the same build failed with the "Import integrity check failed" error.
5. Manual intervention was required to remove both `~/.cache/dhall` and `~/.cache/dhall-haskell`.

It was tricky to find out why it was reporting "Import integrity check failed" error, since `dhall hash` was reporting correct integrity hash.  First we deleted `~/.cache/dhall`, which caused `dhall` to report `DeserialiseFailure 0 "end of input"` error.  That was fixed by removing `~/.cache/dhall-haskell` directory.

Reason behind this behaviour is that `writeFile` is not atomic (<https://github.com/dhall-lang/dhall-haskell/blob/f18ec5f8e0145f8c77a3d59fedd8d0934c0e1bc0/dhall/src/Dhall/Import.hs#L557>).  Correct behaviour (on UNIX-style systems) would be:

1. Create a temporary file in the cache directory.  It has to be the cache directory for security and for renaming operation to be atomic.
2. Write the content of the file and close the file handle.  If write fails, remove temporary file and report an error.
3. Rename the temporary file to `${cacheDir}/${hash}`.  This step can fail for multiple reasons:
    - File `${cacheDir}/${hash}` already exists. This is OK, if it exists something committed it before us.
    - Any other reason means that we need to delete temporary file and report error to the user.

/cc @jcpetruzza

**Comment by Gabriel439** [comment]
@sjakobi: This is another reason to switch to using `UnliftIO.IO.File.withBinaryFileDurableAtomic` as you suggested in https://github.com/dhall-lang/dhall-haskell/issues/498#issuecomment-546527837, which would do what @trskop suggested
