### ISSUE TITLE
"\n" is unexpectedly formatted as a multi-line string

### ISSUE THREAD

**Issue by sjakobi** [dhall-lang/dhall-haskell#1566]
```
$ echo 'fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff xxxxxxxxxxxxxxxx "\n"' | dhall format
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
  xxxxxxxxxxxxxxxx
  ''

  ''
```

I would have expected to get this instead:

```
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
  xxxxxxxxxxxxxxxx
  "\n"
```

**Comment by Gabriel439** [comment]
I thought we always formatted strings as multi-line strings if they had a newline

**Comment by sjakobi** [comment]
Nope, I had made an exception for strings that are _all_ newlines so you could still write

```dhall
Text/concatSep "\n"
```

https://github.com/dhall-lang/dhall-haskell/blob/c3ac963b6e52dc1702997ee5b86c11d6c8630412/dhall/src/Dhall/Pretty/Internal.hs#L1090-L1097

We end up in the `Pretty.flatAlt long short` case here, and I don't understand yet why the layouter ends up preferring the `long` version. The `Doc`s for even such small examples are surprisingly complex.

**Comment by Gabriel439** [comment]
@sjakobi: The mental model I use for reasoning about the `prettyprinter` package is:

* Whenever you express something as `flatAlt long short` you give the `prettyprinter` package the option to pick either the "long" or "short" representation depending on what the layout algorithm prefers
* If you have multiple `flatAlt`s (either nested or as siblings within the document syntax tree) then the `prettyprinter` package can decide differently for each one.  For example, it can choose to render one occurrence of `flatAlt` as "short" and another occurrence as "long"
* If you `group` a document then `prettyprinter` prefers the "short" representation by default if the entire document that you pass to `group` fits within a single line, otherwise it defers to what the surrounding expression prefers (which in turn defaults to the "long" representation if you hit the top-level of the document syntax tree)

We do have several occurrences of `group` within the pretty-printed document, but in the case of your example, there isn't a `group` surrounding the string literal alone.

There is a top-level `group` surrounding the entire application expression, but the entire expression does not fit within a single line, so it renders everything as long form.  However, if you change the code to:

```haskell
 prettyChunks :: Pretty a => Chunks Src a -> Doc Ann 
 prettyChunks chunks@(Chunks a b) 
     | anyText (== '\n') = 
         if not (null a) || anyText (/= '\n') 
         then long 
         else Pretty.group (Pretty.flatAlt long short)
     | otherwise = 
         short 
```

... then I believe it will behave the way you expected.  This is because the `group` wrapping the string literal can now independently check if just the string literal in isolation fits on one line, regardless of whether the surrounding expression fits on one line.

I have a change up implementing this: https://github.com/dhall-lang/dhall-haskell/pull/1569

**Comment by sjakobi** [comment]
Thank you @Gabriel439! That makes a lot of sense! :)

**Comment by Gabriel439** [comment]
@sjakobi: You're welcome! 🙂
