### ISSUE TITLE
dhall format on linux behaves differently than on osx/darwin (dhall 1.28.0)

### ISSUE THREAD

**Issue by amarrella** [dhall-lang/dhall-haskell#1590]
Hi, I think I found a small bug in `dhall format` for which on linux it behaves differently than in darwin.

File to reproduce (`reproduce.dhall`):
```dhall
let Config = { awsAccountId : Text }

let User = { awsRole : Text, k8sRole : Text }

let IAM = { roleARN = λ(role : Text) → λ(account : Text) → role }

let makeFoo =
        λ(config : Config)
      → λ(user : User)
      → ''
        - rolearn: ${IAM.roleARN user.awsRole config.awsAccountId}
            username: ${IAM.roleARN user.awsRole config.awsAccountId}
            groups:
            - ${user.k8sRole}''

in  makeFoo
```

`dhall --ascii format --inplace ` on osx/darwin keeps the file the same

the same command on linux outputs:
```dhall
let Config = { awsAccountId : Text }

let User = { awsRole : Text, k8sRole : Text }

let IAM = { roleARN = \(role : Text) -> \(account : Text) -> role }

let makeFoo =
          \(config : Config)
      ->  \(user : User)
      ->  ''
          - rolearn: ${IAM.roleARN user.awsRole config.awsAccountId}
              username: ${IAM.roleARN user.awsRole config.awsAccountId}
              groups:
          ${"    "}- ${user.k8sRole}''

in  makeFoo
```

which looks weird.

Dhall version for both binaries is 1.28.0 and i'm using the pre-compiled binaries found in the release page.

**Comment by amarrella** [comment]
Sorry i was still on 1.27 on osx....

**Comment by sjakobi** [comment]
Thanks for the report anyway!

The surprising interpolation of the leading whitespace on the last line is due to https://github.com/dhall-lang/dhall-haskell/pull/1550. Apologies for the confusing conversation there: I hadn't really understood the issue until after I had implemented the fix! ;)

The motivation for moving that whitespace into an interpolation is that when _all_ lines of a multi-line string begin with whitespace, the parser can't figure out when those lines are supposed start and ends up removing some indentation. For example

```dhall
"  x\n  y"
```

was being formatted like this before #1550:

```dhall
''
  x
  y''
```

which according to the standard is equivalent to

```dhall
''
x
y''
```

since the beginning of the lines must be marked by a non-whitespace character on one of the lines.

To protect this leading whitespace, I changed the multi-line string formatting to move any leading whitespace on the last line into a string interpolation, so the parser can figure out the correct indentation. Now we get

```dhall
''
  x
${"  "}y''
```

which is equivalent to the original string.

In your example this "indentation protection" isn't strictly necessary:

```dhall
      → ''
        - rolearn: ${IAM.roleARN user.awsRole config.awsAccountId}
            username: ${IAM.roleARN user.awsRole config.awsAccountId}
            groups:
            - ${user.k8sRole}''
```

The first line starts with a non-whitespace character (`-`), which indicates the correct beginning of the line to the parser.

In fact we could change this "indentation protection" to only apply when _all_ lines start with whitespace. Any opinions on that?
