### ISSUE TITLE
dhall-yaml is missing from Hackage

### ISSUE THREAD

**Issue by sjakobi** [dhall-lang/dhall-haskell#1591]
v1.0.0 ought to have been released with https://github.com/dhall-lang/dhall-haskell/releases/tag/1.28.0 but so far there's nothing at http://hackage.haskell.org/package/dhall-yaml.

**Comment by Gabriel439** [comment]
Huh, that is weird.  I'm pretty sure that I uploaded it last night and double-checked it.  However, I also see the same missing package that you do

I just tried to upload it again and got this error:

```
$ cabal upload --publish dist/dhall-yaml-1.0.0.tar.gz 
Uploading dist/dhall-yaml-1.0.0.tar.gz...
Error uploading dist/dhall-yaml-1.0.0.tar.gz: http code 403
Error: Upload failed

You are not authorised to upload new versions of this package. The package
'dhall-yaml' exists already and you are not a member of the maintainer group
for this package.

If you believe you should be a member of the maintainer group for this
package, then ask an existing maintainer to add you to the group. If this is a
package name clash, please pick another name or talk to the maintainers of the
existing package.
```

**Comment by sjakobi** [comment]
Oh, apparently @hvr has registered the package name in some way: https://hackage.haskell.org/package/dhall-yaml/maintainers/

@hvr, do you have plans to publish an own package with this name, or could you possibly transfer it to @Gabriel439?

**Comment by hvr** [comment]
@hvr @Gabriel439 I started preparing a dhall-yaml package and uploaded a package candidate a couple months ago when the dhall/HsYAML debate looked like the dumbfounded GPL FUD arguments would win and render the GSOC's work product in vain. Later I still got disappointed when `dhall-json` ended up not depending on HsYAML by default (whereas we had previously discussed making HsYAML opt-out, not opt-in), so I still held on to `dhall-yaml`.

That being said, I've been made aware by Simon on IRC that you've been working on doing the technically sensible thing yourself and creating a `dhall-yaml` package which can leverage HsYAML's advanced features. So I'm happy to not have to implement `dhall-yaml` myself and pass on ownership to Gabriel (which I've done already) :-)

Btw, HsYAML's license is technically `GPL-2.0-or-later` (it's not that obvious though as I had to use a pre-SPDX cabal-version declaration) while I see you decided to declare it `GPL-3.0-only` (in SPDX lingo) -- did you really intend that (it's totally fine if you do; I just wonder if it was intentional -- the main reason I tend to pick GPL-2.0-or-later is that this way it's compatible to combine with both GPL-2.0 and GPL-3.0 code).

**Comment by Gabriel439** [comment]
@hvr: No worries!  Also, there is no particular reason we put GPL 3.0 only; it was probably an oversight on our part

**Comment by Gabriel439** [comment]
I just uploaded `dhall-yaml` successfully, so I'll mark this closed

**Comment by sjakobi** [comment]
Thanks @hvr! :)
