### ISSUE TITLE
Record completion: spaces or no with `dhall format`?

### ISSUE THREAD

**Issue by SiriusStarr** [dhall-lang/dhall-haskell#1593]
This is not so much an issue as a gauge of public opinion, but with the inclusion of #1532 (and by extension dhall-lang/dhall-lang#820), the question should be asked: *should* `dhall format` place spaces around the record completion operator (`::`) or not?  Currently it strips them out.

As far as I see it, on one side you have the "projection" operator (`.`), which does not get spaces.

On the other, you have every other record operator (`/\`, `//\\`, `//`), which do get spaces around them.

My gut leans towards the latter, as completion to me seems most analogous to the `//` operator (which gets spaces).

**Comment by sjakobi** [comment]
`::` is actually similar to `.` in that it's non-associative. All the other operators are associative.

**Comment by SiriusStarr** [comment]
True!  I guess mentally my brain cares less about associativity and more about "Does this 'update/extend' vs 'zoom in on' ".  Clearly I am not sufficiently math-oriented.  XD

**Comment by Gabriel439** [comment]
There is an easy way to distinguish which operators get surrounding spaces and which ones don't: the operators that are higher-precedence than function application don't get surrounding spaces and the operators that are lower-precedence than function application get spaces

So `::` and `.` are both higher-precedence than function application, which is why they don't get surrouding spaces

**Comment by SiriusStarr** [comment]
> the operators that are higher-precedence than function application don't get surrounding spaces and the operators that are lower-precedence than function application get spaces

Should spaces really have been allowed around the completion operator in that case?

**Comment by Gabriel439** [comment]
@SiriusStarr: Yes, for the same reasons that we allow spaces around the `.` operator:

* Users might want to opt out of the behavior

  e.g by not formatting the code at all or (in theory) creating a new formatter to compete with `dhall format`

* Tolerating weirdness in the grammar lets code authors be sloppy when authoring code so that they can trust the formatter to fix it

  In other words, if spaces surrounding the operator were a parse error, then the formatter would be unable to fix them

  This also makes it easier for people to write (textual) code generators if they don't have to be careful about where the code generator inserts whitespace or parentheses

* Just because code is unformatted doesn't mean it should be illegal code

  As a simple example: `(Natural/even 1)` is not formatted, due to the extra parentheses, but it wouldn't make sense to treat the gratuitous parentheses as a parse error

**Comment by SiriusStarr** [comment]
Ahhh, I legitimately had no idea that spaces were allowed around `.`, derp.

**Comment by SiriusStarr** [comment]
Well, delete this issue then.
