### ISSUE TITLE
`dhall lint` should fix property assertions too

### ISSUE THREAD

**Issue by sjakobi** [dhall-lang/dhall-haskell#1594]
For example we currently have

```
$ echo 'let p = \(x : Natural) -> (x + 0) === x in 1' | dhall lint
1
```

It would be nice to get

```dhall
let p = λ(x : Natural) → assert : (x + 0) ≡ x in 1
```

instead.

**Comment by Gabriel439** [comment]
@sjakobi: This one I'm not as sure about, because not all definitions of that form are necessarily intended to be property tests

For example, a user might use such a function to create a list of unit tests, like this:

```dhall
let test = λ(n : Natural) → Natural/even (n + n) === True
  
let tests =
        [ assert : test 0
        , assert : test 1
        , assert : test 2
        , assert : test 3
        ]

in  tests
```

**Comment by sjakobi** [comment]
Hmm, indeed. I think the same concern applies to the existing rules for equivalences in let-bodies:

https://github.com/dhall-lang/dhall-haskell/blob/30d9345fc994bb3b1d4a722bb3bafa60d6d89e9f/dhall/src/Dhall/Lint.hs#L69-L70

Maybe this is something that could be disabled with a CLI option?

`--fix-asserts={conservative,eager}` with `eager` as the default?

**Comment by Gabriel439** [comment]
In general, I don't think that `dhall lint` should accept lint-related options since a lot of the value it provides is due to it being opinionated.  Usually for anything that requires human judgment I think it belongs in the `dhall-lsp-server` as suggestions for how to fix the code

However, maybe we should actually get rid of the current rules for fixing equivalences, since (like you mentioned), even they are potentially dangerous.  We could instead move them into `dhall-lsp-server`

**Comment by sjakobi** [comment]
So far I was under the impression that what `fixAsserts` does is quite useful. I also haven't heard of any complaints that it would produce assertions where they weren't desired.

Having `fixAsserts` in `dhall lint` also means that it can be used e.g. in CI, where `dhall-lsp-server` can't be used as easily.

However if we'd remove `fixAsserts`, we'd still have `removeUnusedBindings` which also points out many equivalences that ought to be assertions.

So I'd suggest that we wait for reports of `fixAsserts` causing problems and then consider removing `fixAsserts` from `dhall lint`. I think there could also be other solutions, such as a naming scheme (e.g. `example.*`) for assertions…

**Comment by Gabriel439** [comment]
@sjakobi: Yeah, the intention is that `dhall lint` is used in CI, which is why I try to ensure that its suggestions are unambiguous improvements.  Even when I introduced `fixAsserts` I had some reservations that it could potentially be problematic in some corner cases, but I agree that we should wait and see

In the case of fixing functions I think there is a greater risk that we run into a problematic correction because I can easily see how somebody might write a function that returns an assertion that they don't want to be rewritten (such as the initial example I gave)
