### ISSUE TITLE
What important thing needs to be solved in HNix to allow better Dhall integration

### ISSUE THREAD

**Issue by Anton-Latukha** [dhall-lang/dhall-haskell#1678]
I am kinda in search, what task to pick next in HNix.

What you consider the shortcoming of the HNix that can&should be solved?

**Comment by sjakobi** [comment]
Thanks for asking! Personally, I don't have any feature requests, but I would love to see a release that is [compatible](https://github.com/haskell-nix/hnix/pull/535) with the latest `prettyprinter` and GHC. That would greatly simplify building and packaging `dhall-nix`.

BTW I just attempted building `hnix` from Hackage and got this:

```
Nix/Expr/Types.hs:76:3: error:
    ‘showsPrec1’ is not a (visible) method of class ‘Show1’
   |
76 |   showsPrec1 = showsPrec
   |   ^^^^^^^^^^
```

**Comment by Gabriel439** [comment]
@Anton-Latukha: The number one thing `hnix` can improve upon would not be a specific feature, but rather just a regular release cadence.  The last release to Hackage was almost a year ago

**Comment by Anton-Latukha** [comment]
I've chatted with John, he basically stated that HNix does not build for all the conditions he requires.

I would investigate that and tend to it, and then would form a release.

**Comment by Gabriel439** [comment]
@Anton-Latukha: While you are looking for ways to improve `hnix`, codifying those supported platforms/environments in CI would help prevent this from recurring in the future.  For example, for Dhall we use CI to ensure that no pull request is merged that breaks any supported platform or any supported GHC.

**Comment by Anton-Latukha** [comment]
@Gabriel439

I know, I know.

I am also, well, probably was, a Nix DevOps at Serokell.

It can be quite hard to squeeze into free Travis norms what is needed for Haskell, but that is understandable `for free`.

Especially when Travis, AFAIK, failed miserably some times. Hope they fixed their networking issues for nodes.

Also back in the day I experienced the pains of Nix deployment. Not one of my fixes or bug reports was addressed in Nix itself, all got or blocked, or ignored. So my bunch of PRs grew, and I had no choise to create an epic PR where I paid in time and effort and improved upon the official installer to the point of transforming it into a good robust Nix installer that also corresponds to POSIX standards, and as such - can run on every POSIX-compatible platform, and then with special cases - on other platforms. So at NixCon 2017 I gave a talk and shown the state of upstream, and issues from my practice in basic cases and from logic, and then my ready solution, and pushed that case for couple of years - but all that resulted into nothing and a lot of nitpicking, like the phrasing of Strings. And last I checked Nix upstream installation was still a mess, it had 3-5 installers that have a code duplication, maybe they at least fixed the basics of container installation for people. I got the perception that I was somehow seen as "not worthy" and "not in the club to take seriously", or Nix has anti-agenda to be installed on other Linux distributions. Or it is just a case of overlooking, trust to risk a bit on migration. In that time of waiting, I learned Haskell and had a personal motivation for HNix.

Overall, yes, property testing and CI.

What CI would you recommend currently for free Haskell projects, I see you use both Travis and Appveyor.

**Comment by Gabriel439** [comment]
@Anton-Latukha: I think it depends on what John needed to support before releasing.  It's not clear to me if that means operating systems, GHC versions, GHCJS, etc.

**Comment by Anton-Latukha** [comment]
@Gabriel439

Of course - it is a general question.

**Comment by Gabriel439** [comment]
@Anton-Latukha: Probably the biggest constraint is whether or not CI needs to test Windows or OS X, since build machines for those are harder to come by.  We currently use AppVeyor for Windows builds and Travis for OS X builds since they are free.  For Linux you can basically use any CI provider, but in this case I pay for a Linode VM which I use to host all Dhall-related infrastructure (i.e. all of the *.dhall-lang.org domains), so I reuse that to host Hydra for Nix-related CI so that I can use more parallelism and more efficient caching to test a wider range of GHC versions on a budget.

For testing OS X and Windows platforms we use `stack`.  The main reason we don't use Nix for either platform is that Nix only supports building release binaries on Linux (and even then it's still experimental).

So the basic summary I can give is:

* For testing everything other than cross-platform support: Nix + Linux is best in my opinion

  ... because you get much more control and intelligent build caching, which is usually where most CI solutions fall short

* For cross-platform support: `stack` + whatever CI provider provides free builds for that platform

Also, if you ever can pay for your own NixOS VM and you want to reuse the setup I built, you can find the NixOS configuration for dhall-lang.org here:

https://github.com/dhall-lang/dhall-lang/tree/master/nixops

**Comment by Anton-Latukha** [comment]
Thank you. Very to the point. This information worth a dedicated article (blog post) in itself, but may not worth an effort of the high-quality articles, as it is the current state of affairs.

**Comment by Gabriel439** [comment]
@Anton-Latukha: You're welcome! 🙂

**Comment by Anton-Latukha** [comment]
@Gabriel439 Can I add it as your quote in my docs?

**Comment by Gabriel439** [comment]
@Anton-Latukha: Yeah, definitely! 🙂

**Comment by Anton-Latukha** [comment]
@Gabriel439 Thank you, here is where quote is used https://blog.latukha.com/haskell-notes#org2762ac0
