### ISSUE TITLE
Different versions of Dhall generate a different import hash

### ISSUE THREAD

**Issue by craig-day** [dhall-lang/dhall-haskell#1715]
It appears that different versions of dhall compute the semantic hash for imports differently. I ran into a problem earlier today where I was running dhall `v1.29.0` and I tried to compile a number of of files and received the following error: 

```
Error: Import integrity check failed
Expected hash:
↳ 180d42d1d90c5d4b55f1d5e7e7cdc1945784b0f77f78d0b9bc13f35cdb3ae68c
Actual hash:
↳ 78842ed47d4157b51fd0248e16c8767b96f3a35c238400e0dc5bf27aaae594ab
```

After some digging it turns out that running `brew upgrade dhall` installed `v1.30.0`, and then re-running the same command ended up succeeded. 

Maybe I'm misunderstanding something, but I would think that the semantic hash should be generated based on the code and what it compiles to, not the version of the language used to compile it. Does this seem correct?

**Comment by sjakobi** [comment]
> the semantic hash should be generated based on the code and what it compiles to, not the version of the language used to compile it.

Changes in the language can affect how Dhall is normalized and hashed.

I don't see much that would have changed between v1.29 and v1.30, so I'm wondering what happened in your case. Do you see any differences when you normalize the import?

**Comment by Gabriel439** [comment]
@craig-day: To answer your question: the hashing algorithm itself does not change in breaking ways that often, but the way things are normalized can change in small ways between language versions and that can affect the hash (since it's a hash of the normal form).  For example, if you search for the words "technically breaking change" on this page:

https://github.com/dhall-lang/dhall-lang/releases

… you will find a few examples of that, like this:

> This is a technically breaking change because the normal forms for certain
expressions will differ if they relied on fusion, which in turn would perturb
semantic integrity checks protecting those expressions. In practice, you are
unlikely to be affected by this change.

However, the `dhall-1.29.0 → dhall-1.30.0` upgrade should have no such breaking changes to the hash that I'm aware of since the normalization algorithm was not changed, nor was the hashing algorithm changed.

I have some guesses to what may have happened, but the way to narrow things down more quickly would be to do the following:

* Interpret the underlying import with version 1.29.0 and then version 1.3.0 and save the result for each version.  Then compare both results using `dhall diff`
* If there was no difference in the previous step, then feed the import to `dhall --alpha | dhall encode --json` with version 1.29.0 and then version 1.30.0 and compare the results using ordinary `diff`

Alternatively, if you have a small expression that you can share with us that has different hashes before and after the upgrade we can compare ourselves.

**Comment by craig-day** [comment]
Thanks for all the info. I'll try running some of those commands today to see where the diff falls. If I can narrow it down to a small reproducible set then I'll provide those examples as well.

**Comment by Gabriel439** [comment]
@craig-day: Is this still an issue?

**Comment by sjakobi** [comment]
I presume this can be closed.

Please re-open if there's more to do or discuss here.
