### ISSUE TITLE
Buggy subtraction in live demo

### ISSUE THREAD

**Issue by andrewthad** [dhall-lang/dhall-haskell#1763]
I was playing around with the live demo and noticed that this works fine:

```
Natural/subtract 11 7
```

It gives 0 as expected, but this does not work:

```
Natural/subtract 7 11
```

I see this JavaScript error in the developer console: `arithmetic underflow`. Probably just an issue with the implementation of subtraction in the JavaScript dhall client, but it breaks the demo an the homepage, so I thought it would be worth opening here.

**Comment by Gabriel439** [comment]
We've run across this issue a few times, so I opened an issue against GHCJS:

* https://github.com/ghcjs/ghcjs/issues/782

Basically, the bug is triggered any time we subtract two `Natural` numbers when using GHCJS.  However, I know how to work around it, which is to use `Integer`s for the subtraction instead.

We've run into this issue before:

* https://github.com/dhall-lang/dhall-haskell/pull/985

**Comment by Gabriel439** [comment]
Fix is up here: https://github.com/dhall-lang/dhall-haskell/pull/1765
