### ISSUE TITLE
Type mismatch error messages on binary operators

### ISSUE THREAD

**Issue by german1608** [dhall-lang/dhall-haskell#1819]
When I execute:
```
dhall <<< `{ a: Natural } // { b : Bool }`
```
I get the following error message (it should fail, as expected):
```
Error: You can only override records

1│                // { b : Bool }

(input):1:15
```
If I change it to the following:
```
dhall <<< '{ a: Natural } // { b = Bool }'
```

it outputs the following:

```
Error: You can only override records

1│                // { b = Bool }

(input):1:15
```

which doesn't shows clearly the source of the error.

It happens whenever the left side of the operators are not records.

**Comment by sjakobi** [comment]
Nice catch!

I think the issue might extend to most (all?) operator expressions? E.g.

```
$ echo 'True + 1' | dhall

Use "dhall --explain" for detailed errors

Error: ❰+❱ only works on ❰Natural❱s

1│      + 1

(input):1:5
```

Looks like we ought to fix the source span in the parser, similarly to what we do in `applicationExpression`:

https://github.com/dhall-lang/dhall-haskell/blob/f49e2733554b8eb6d74799620111a8c8f3571d43/dhall/src/Dhall/Parser/Expression.hs#L381-L386

I also wonder whether this is just a regression, possibly due to https://github.com/dhall-lang/dhall-haskell/commit/eb895bc538e8a2307d81a841f1f042ed6dbf8b80.

BTW, I wanted to use `dhall haskell-syntax-tree` to look at the issue, but that unfortunately strips the `Note` constructors:

```
$ echo 'a // b' | dhall haskell-syntax-tree
Prefer PreferFromSource
    ( Var ( V "a" 0 ) )
    ( Var ( V "b" 0 ) )
```

It would be nice to have a `--noted` mode or similar for cases like these…

**Comment by Gabriel439** [comment]
Fix is up here: https://github.com/dhall-lang/dhall-haskell/pull/1824
