### ISSUE TITLE
Relative path not working correctly

### ISSUE THREAD

**Issue by zzat** [dhall-lang/dhall-haskell#1831]
I have the following directory structure:
```
|- main.dhall
|- dir1
    |- foo.dhall
|- dir2
    |- bar.dhall
```
```
-- main.dhall
/tmp/dir1/foo.dhall
```
```
-- foo.dhall
./bar.dhall
```
```
-- bar.dhall
10
```
I want `foo.dhall` to load `bar.dhall` relative to the root I supply in settings (`dir2`). So I run it like:
```
cfg <- T.readFile "/tmp/main.dhall"
let sett = defaultInputSettings & rootDirectory %~ \_ -> "/tmp/dir2/"
inputWithSettings sett auto cfg :: IO Natural
```
But it fails as it tries to find `bar.dhall` relative to `foo.dhall`'s directory. 
```
Error: Missing file /tmp/dir1/bar.dhall
```
Isn't this supposed to work?

**Comment by sjakobi** [comment]
I think the content of `foo.dhall` should be `../dir2/bar.dhall`.

**Comment by Gabriel439** [comment]
@zzat: The `rootDirectory` only affects the directory used to interpret the top-level expression.

In your example, the top-level expression is the `cfg` string, which is `"/tmp/dir1/foo.dhall"`.  Since that import is an absolute path the `rootDirectory` is ignored and subsequent imports will be relative to `/tmp/dir1`.  The `rootDirectory` does not affect the behavior of transitive imports.

**Comment by Gabriel439** [comment]
I'll close this as I believe the question was addressed.  Feel free to reopen if you still have additional questions
