### ISSUE TITLE
What to do with packages that doesn't have a package.dhall file?

### ISSUE THREAD

**Issue by german1608** [dhall-lang/dhall-haskell#1836]
I looked at [awesome-dhall](https://github.com/dhall-lang/awesome-dhall) libraries section and I extracted the following information for each listed package:

|Name                     |Has a package.dhall?|
|-------------------------|--------------------|
|dhall-prelude            |Yes                 |
|dhall-kubernetes         |Yes                 |
|dhall-kong               |No                  |
|dhall-terraform          |No                  |
|dhall-nethack            |No                  |
|dada                     |No                  |
|dhall-bhat               |No                  |
|github-actions-dhall     |No                  |
|dhall-kops               |Yes                 |
|dhall-prometheus-operator|Yes                 |
|dhall-genode             |Yes                 |
|dhall-openssl            |Yes                 |
|nats.dhall               |Yes                 |
|dhall-ansible            |Yes                 |

Will `dhall-docs` only work with packages that has a package.dhall? What should the tool do if there is no package.dhall file?

**Comment by Gabriel439** [comment]
@german1608: There are two solutions I can think of:

* Have the tool provide an option to specify a non-default entry point.  For example, the `dhall-to-nixpkgs` tool takes a `--file` option for this purpose
* Require a `dhall` package to have a `package.dhall` in order to be able to use the tool (in which case, `package.dhall` could trivially re-export some other file if desired)

I slightly prefer the former approach

**Comment by Gabriel439** [comment]
I'll close this as I believe the question was resolved
