### ISSUE TITLE
dhall-docs: Rendered source code should preserve token positions from the original .dhall file?

### ISSUE THREAD

**Issue by german1608** [dhall-lang/dhall-haskell#1866]
In my proposal timeline I wrote that next step after markdown generation was to add the "Jump to definition" feature, but I'd like to start first with rendered source code.

In order to add syntax colors in the rendered source code, would you mind if the token positions are not the same as in the original file?

The simplest I can think to do this task is to traverse the AST and transform it to html, where each token has its correspondent class name.

**Comment by sjakobi** [comment]
> In my proposal timeline I wrote that next step after markdown generation was to add the "Jump to definition" feature, but I'd like to start first with rendered source code.

Sounds good to me.


> In order to add syntax colors in the rendered source code, would you mind if the token positions are not the same as in the original file?

I don't really understand the question (possibly because I'm a bit tired! ;)). Could you illustrate what the token positions are in this case, and how they would change?

**Comment by german1608** [comment]
> > In order to add syntax colors in the rendered source code, would you mind if the token positions are not the same as in the original file?
> 
> I don't really understand the question (possibly because I'm a bit tired! ;)). Could you illustrate what the token positions are in this case, and how they would change?

Say that a sample file is something like this:

```dhall
let a
  = 1

in

  a + 1
```

Do you mind if the rendered source code doesn't preserve the original whitespaces (like `dhall lint` does for example) or it should be the same as the original source?

I ask because I think that the simplest solution to add syntax-highlighting is to traverse the AST and build `<span>` html elements with correspondent classes for each posible token, and if it should handle whitespace as well then I should also add the whitespace in the html, which might be tricky to get right. Probably I'm overthinking it... maybe it will be easier once I start coding it. But anyways, what do you think will be better?

**Comment by sjakobi** [comment]
Oh, you mean whether the code can be reformatted, as if it was piped through `dhall format`? I suspect that this would probably be easier implement indeed.

One possibility would be to implement that initially, and if it turns out that the users want to preserve the original formatting, we can try to implement that too. (I suspect that users will request this since quite a few don't like the output of `dhall format`.)

If we decide to reformat the code, we should try to reuse the existing pretty-printer, by rendering its output to HTML. There's a small tutorial on this [here](http://hackage.haskell.org/package/prettyprinter-1.6.1/docs/Data-Text-Prettyprint-Doc-Render-Tutorials-TreeRenderingTutorial.html).

OTOH, I have also wondered how to recover the original formatting from the `Src` annotations. I wonder whether there's some clever trick that might make annotating the code in its original formatting not so difficult after all…

**Comment by sjakobi** [comment]
Also note, that we can definitely implement this initially without any syntax highlighting or reformatting. 

Just to include the original code would be a nice feature.

**Comment by sjakobi** [comment]
@german1608 You could also take a look at syntax highlighting libraries like http://hackage.haskell.org/package/skylighting.

**Comment by german1608** [comment]
@sjakobi thanks for all your input and resources!

**Comment by Gabriel439** [comment]
I also think it's fine if we don't preserve the original whitespace for now

**Comment by german1608** [comment]
I'll close this issue meanwhile, since I'm more guided by your thoughts now

May open again in the future
