### ISSUE TITLE
dhall-docs symlinks strategy

### ISSUE THREAD

**Issue by german1608** [dhall-lang/dhall-haskell#1870]
I've been thinking a little bit about generating the documentation like nix does for its packages, using symlinks. So I'll use this issue for a first proposal with the details of how it will be done, where docs will be saved and so on.

## Where docs will actually be saved?

`dhall-docs` will have a reserved folder in the filesystem to save its documents. I propose we use `$HOME/.dhall-docs` for it. There can be an environmental variable to override it, I see `DHALL_DOCS_STORE` as a good name.

Now, each package needs to have its own directory inside that `DHALL_DOCS_STORE`. I suggest using the package-name, extracted as the currently the tool does:

* Via the `--package-name` configuration flag, or
* Using the basename of the input directory.

Wo, for a package named `PACKAGE_NAME`, its documentation will be saved on `$DHALL_DOCS_STORE/$PACKAGE_NAME`.

## How it will be done

Actually, it will be the same as we currently do, but saving at `$DHALL_DOCS_STORE/$PACKAGE_NAME`. After that, the tool will wire up the symlinks and configure them in the output folder that the user specified. Note that the `--output` is different from `$DHALL_DOCS_STORE/$PACKAGE_NAME`, the prior just contains symlinks unlike the latest that contains the actual documentation.

i'll be aware of your thoughts

**Comment by mmhat** [comment]
If you want to do Nix-like symlinking maybe [cas-store](https://hackage.haskell.org/package/cas-store) might be a good source to take inspiration from.
Since I don't have the time right now to follow your efforts (Thanks anyway!) I hope this hint is not too misplaced.

**Comment by ari-becker** [comment]
Instead of using `$HOME/.dhall-docs`, please consider using the [XDG Base Directory specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) and use `$XDG_CACHE_HOME/dhall-docs` or `$HOME/.cache/dhall-docs` if `$XDG_CACHE_HOME` is empty. Using the XDG Base Directory specification helps users keep a cleaner home directory.

If I misunderstood and the docs directory is not really considered a cache, then use `$XDG_DATA_HOME/dhall-docs` or `$HOME/.local/share/dhall-docs` instead.

**Comment by german1608** [comment]
@ari-becker 
> If I misunderstood and the docs directory is not really considered a cache, then use `$XDG_DATA_HOME/dhall-docs` or `$HOME/.local/share/dhall-docs` instead.

Yes, the docs directory isn't really a cache. Thanks for your suggestion about the XDG specification.

**Comment by Gabriel439** [comment]
@german1608: Yeah, I'm in favor of this.  The only suggestion I have is to include the package version and a hash of the output directory in the name of the generated directory (to make it content-addressable, similar to what @mmhat suggested)

**Comment by german1608** [comment]
> The only suggestion I have is to include the package version 

Well in this moment there is no notion of dhall packages version, so we could add it after defining an spec for dhall packages.

**Comment by german1608** [comment]
@Gabriel439 Why a hash of the output instead of a hash of the input?

**Comment by Gabriel439** [comment]
@german1608: The general reason is so that the cache is content addressable.  One reason a content-addressable cache is desirable is because you never need to invalidate the cache.

For example, consider the following scenario which a user might run into if you were to hash the input:

* The user runs `dhall-docs-1.0.0` to generate documentation for their package
* They upgrade to `dhall-docs-2.0.0` (which changes how the documentation is generated)
* The run `dhall-docs-2.0.0` on their documentation, which links to the prior (stale) documentation from their local cache which was generated by `dhall-docs-1.0.0` (because the input hasn't changed)

This problem would not have occurred if `dhall-docs` had hashed the output rather than the input.
