### ISSUE TITLE
Record can no longer contains attribute named after language keywords

### ISSUE THREAD

**Issue by TristanCacqueray** [dhall-lang/dhall-haskell#1896]
Since https://github.com/dhall-lang/dhall-haskell/commit/f33c0f819ca98b1a241bc59ec6bfdb84e866cba4 it seems like `as` and `assert` are no longer valid attribute names. I guess this is a bug fix with regards to the standard, but that was a breaking change for the `dhall-openshift` (https://github.com/TristanCacqueray/dhall-openshift/issues/4) and `dhall-ansible` binding.

Does the offending keywords needs to be escaped using backticks, e.g.: `{ as = 42 }` ->
```
{ `as` = 42 }
```
?

**Comment by Gabriel439** [comment]
@TristanCacqueray: Yeah, that is correct.

This was the standardized behavior for a while, but the Haskell implementation was not standards-compliant.  The relevant bug was:

https://github.com/dhall-lang/dhall-haskell/issues/1750

... and the relevant fix was:

https://github.com/dhall-lang/dhall-haskell/pull/1801

... which means that code needs to escape record fields that match keywords using backticks

**Comment by TristanCacqueray** [comment]
Alright, so I guess something needs to happen for dhall-kubernetes-generator to prevent such issue. @Gabriel439 , do you think https://github.com/dhall-lang/dhall-kubernetes/blob/master/dhall-kubernetes-generator/src/Dhall/Kubernetes/Convert.hs#L141 needs to check for `reservedKeywords` ? Or is this something dhall `prettyExpr` should do automatically?

**Comment by Gabriel439** [comment]
@TristanCacqueray: This should be as simple as updating `dhall-kubernetes` to the latest `dhall` version since newer versions of `dhall` will quote record fields that match reserved keywords

**Comment by jfroche** [comment]
We didn't face the problem until the moment we removed our dhall caches (in `~/.cache/dhall` & `~/.cache/dhall-haskell`). Is is a general advice to remove our cache when we upgrade dhall (/dhall-to-json/dhall-to-yaml) version ?
Or is there a way to have a "dhall versioned" cache ?

**Comment by Gabriel439** [comment]
@jfroche: The issue wasn't due to the cache being version-specific; the cache you had works with both versions of the interpreter.

The reason you only observed the problem when you deleted the cache was because the interpreter was not resolving transitive dependencies (since they were cached).  Once you deleted the cache the interpreter began to load transitive dependencies and detected that they were no longer compatible with the current interpreter version.

**Comment by Gabriel439** [comment]
@jfroche: Also, I forgot to answer your general question of whether or not the caches need to be invalidated upon upgrade

You should never need to delete or otherwise invalidate `~/.cache/dhall` for two reasons:

* It is a content-addressable cache (and one nice property of content-addressable caches is that they never need to be invalidated)
* Even if some out-of-band process were to corrupt the cache (e.g. disk failure or power outage), the interpreter will automatically repair the cache

In contrast, `~/.cache/dhall-haskell` is not content-addressable, so there may be some circumstances where it may need to be invalidated, but hopefully they are rare.  Also, because it is not content-addressable we cannot automatically detect and repair corruption like we do for `~/.cache/dhall`

**Comment by jfroche** [comment]
Thank you once again for the clear explanations

**Comment by TristanCacqueray** [comment]
I added the backtick by hand to my packages, and dhall-lang/dhall-kubernetes#127 seems to work too. Thank you for the explanations.
