### ISSUE TITLE
dhall-docs tests failing on Windows

### ISSUE THREAD

**Issue by german1608** [dhall-lang/dhall-haskell#1903]
`dhall-docs` tests are failing on Windows, as this appveyor report says:

https://ci.appveyor.com/project/Gabriel439/dhall-haskell/builds/33971268

(found on #1901)

**Comment by Gabriel439** [comment]
@german1608: The `openTempFile` error is due to naming the test after the file path:

https://github.com/dhall-lang/dhall-haskell/blob/e22ecde05f3cb858a0d5695dcd3ba3466b62cec2/dhall-docs/tasty/Main.hs#L59

This is because in the course of printing the diff `tasty-silver` uses the test name as the template string for a temporary file here:

https://github.com/phile314/tasty-silver/blob/1f511d2d84ccd0be3adac70c5b88a6dd791f309c/Test/Tasty/Silver/Interactive.hs#L223-L224

... and the logic for creating the temporary file doesn't like path separators in the template string.

If you fix that then the test failure will get further and display the actual diff that is causing the test to fail

**Comment by RoyiAvital** [comment]
Sorry for the interrupt, is there a guide on how you managed to compile a Nix + Haskell project for Windows.
I'd like to replicate it for the https://github.com/srid/neuron project by @srid.

**Comment by Gabriel439** [comment]
@RoyiAvital: We only use Nix to build release binaries for Linux.  For OS X and Windows we use `stack` to build the release binaries on Travis / Appveyor respectively

**Comment by RoyiAvital** [comment]
@Gabriel439 , Could you point me to see how?
@srid , Do you know `stack`?

**Comment by RoyiAvital** [comment]
@Gabriel439 , do you mean this: https://docs.haskellstack.org ?

**Comment by Gabriel439** [comment]
@RoyiAvital: Yes

**Comment by Gabriella439** [comment]
Yeah, this issue is no longer relevant.  The `dhall-docs` tests have been green for a while now and we don't use appveyor at all.

**Comment by kukimik** [comment]
How about removing `appveyor.yaml` (and `.travis*`, if Travis is also no longer in use)? I think their presence may be confusing. If needed they can be restored using the VCS.

**Comment by RoyiAvital** [comment]
Hi, I retried now on Windows + Python 3.12 using `conda-forge` (I use Micro Mamba instead of Conda) and it works!

Thanks for the effort.
