### ISSUE TITLE
dhall-to-yaml Is it possible to emit "raw" strings?

### ISSUE THREAD

**Issue by horkhork** [dhall-lang/dhall-haskell#1938]
I'm currently investigating using Dhall to generate YAML documents to be used as test imports for the Tavern API testing tool (https://tavern.readthedocs.io/). I'm bumping into a problem that I need some assistance with.

Tavern has the notion of 'directives' that are bare strings prefixed with a '!', e.g.:

```
includes:
  - !include auth_stage.yaml
```

Tavern does some non-standard YAML processing in order to make this work, and requires that these strings NOT be enclosed in quotes.

Is it possible to create custom string formatting in Dhall to allow for outputting the above YAML fragment?

Thanks in advance! Dhall is pretty neat, thanks for creating it!

**Comment by sjakobi** [comment]
After a bit of searching it seems to me that `!include` is a [local YAML tag](https://yaml.org/spec/1.2/spec.html#id2784064). I don't understand how it's used though.

I think there's no Dhall construct that corresponds to YAML tags. Maybe we could support it similarly to how we use  [`Nesting`](https://github.com/dhall-lang/dhall-lang/blob/v17.0.0/Prelude/JSON/Nesting) to support different styles for unions.

Allowing strings that start with `!` to be rendered without quotes seems like a rather unprincipled approach to me.

Also, instead of using `includes`, can't you simply inline `auth_stage.yaml` or the corresponding Dhall expression?

**Comment by sjakobi** [comment]
For reference, here are the docs for `!include`: https://tavern.readthedocs.io/en/latest/basics.html#including-external-files

If this is about sharing common data, I suspect that you should rather use Dhall's support for imports.

**Comment by horkhork** [comment]
Thanks for the extremely prompt response!

I have been considering work arounds similar to your suggestion to solve the sharing common data problem. There are some other cases where support for Node Tags could be useful - https://tavern.readthedocs.io/en/latest/basics.html#matching-arbitrary-return-values-in-a-response

But I think I can work around this for now.
