### ISSUE TITLE
`dhall format` breaks working code with toMap in an import

### ISSUE THREAD

**Issue by kubukoz** [dhall-lang/dhall-haskell#1998]
Hi!

This code works perfectly fine in the REPL:

```dhall
https://httpbin.org/headers using (toMap { TOKEN = "AAAA" }) as Text
```

But running it through `dhall format` removes the `()` surrounding `toMap`, and the code stops parsing:

```shell
⊢ ./example.dhall

↳ ./example.dhall

Error: Invalid input

/Users/kubukoz/IdeaProjects/pitgull/example.dhall:1:7:
  |
1 | https://httpbin.org/headers using toMap { TOKEN = "AAAA" } as Text
  |       ^^
unexpected "//"
expecting whitespace


1│ ./example.dhall

(input):1:1
⊢
```

**Comment by sjakobi** [comment]
Thanks for the report! This is somewhat related to https://github.com/dhall-lang/dhall-haskell/issues/1925 where we also discuss possible solutions.

I think your best bet is to either stick to record literals for the headers or try using `netrc` files instead of Dhall's HTTP header support.

HTTP headers currently seem likely to be removed from the language. See https://github.com/dhall-lang/dhall-lang/issues/543.

**Comment by Gabriel439** [comment]
@sjakobi: Actually, this is a separate issue which we can fix, and I have a pull request up for this here: https://github.com/dhall-lang/dhall-haskell/pull/2000

**Comment by kubukoz** [comment]
Using a .netrc file will be problematic for me, as I'll be calling `dhall-to-json` programatically to acquire configuration from a user's repository - I was planning to rely on headers to pass the access token to e.g. the gitlab API. Having to use extra config files means the process becomes more stateful and harder to reason about.
