### ISSUE TITLE
Providing default values for undefined ENV values

### ISSUE THREAD

**Issue by SkyWriter** [dhall-lang/dhall-haskell#204]
I was wondering if there's a way to provide default values for undefined (or possibly blank) environment variable values.

E.g. say I have a default service URL value of "http://some.svc/", but I want to be able to override it with a `SERVICE_URL` env variable.

Looking at the code I figure there's an exception thrown as soon as `lookupEnv` fails, which seemingly eliminates possibilities of handling it within Dhall domain. Or am I just missing something?

**Comment by Gabriel439** [comment]
Yeah, I think this is a good idea although I may not make the change until after the first draft of standardizing the language semantics

Could you re-open this issue in this other repository:

https://github.com/dhall-lang/dhall-lang

Since that is where discussions of the language standard go whereas this repository is now focused on issues related to the Haskell implementation of Dhall

**Comment by SkyWriter** [comment]
Thanks for the feedback. I've created https://github.com/dhall-lang/dhall-lang/issues/70 instead.
