### ISSUE TITLE
Interpolation and files imported as Text

### ISSUE THREAD

**Issue by mmhat** [dhall-lang/dhall-haskell#2078]
Consider this a Bash script called `test.sh` with the following content:
```
#!/usr/bin/bash

cat <<EOF
echo '${1}'
EOF
```

Now if we run `dhall <<< "./test.sh as Text"` we get
```
''
#!/usr/bin/bash

cat <<EOF
echo '''${1}'
EOF
''
```

Note that `'${1}'` is not escaped properly. In particular `dhall <<< "./test.sh as Text" | dhall` errors complaining that you can only interpolate Text.

I expected that `as Text` imports the `test.sh` as raw text, i.e. without interpolation.

**Comment by Gabriel439** [comment]
@mmhat: The import is working fine (meaning that the import is being imported as raw text).  If the import had not been treated as raw text then the import would have failed (because `test.sh` is not a valid Dhall expression).

The issue is that the `'${1}'` is not being escaped correctly by the pretty-printer correctly.  Normally the way to escape `${x}` in a multi-line `Text` literal is to prefix it with two single quotes (i.e. `''${x}`), but the issue is that there is already another single quote before that, leading to three single quotes in a row (`'''`), which is itself a separate escape sequence for two single quotes in a multi-line string literal.

Fortunately, this should be easy to fix by changing the pretty-printer to render the string to something like this:

```
''
#!/usr/bin/bash

cat <<EOF
echo ${"'"}''${1}'
EOF
''
```
