### ISSUE TITLE
dhall-format produces infinite output when using the new "constructors" keyword.

### ISSUE THREAD

**Issue by benjamin-travis-summers** [dhall-lang/dhall-haskell#209]
This breaks, for example:

https://github.com/benjamin-travis-summers/yi-config/blob/36d7e97f8904bb2dac3025e826efb67a636f64e0/Config.dhall

**Comment by Gabriel439** [comment]
Thanks for catching this!  I can fix this

**Comment by Gabriel439** [comment]
One person has asked for good beginner tickets, so I'll use this as an example one to get started.

The bug here is that the `pretty{...}` and `build{...}` functions in `Dhall.Core` trigger an infinite loop if you don't update them when adding new constructors to the `Expr` AST.  Adding a case to handle the `Constructors` constructor will make the infinite loop disappear.

**Comment by Gabriel439** [comment]
Actually, looking into this, my initial diagnosis is incorrect.  There is logic there for pretty-printing the `Constructors` keyword but it is broken.
