### ISSUE TITLE
Poor record projection error message

### ISSUE THREAD

**Issue by thebritican** [dhall-lang/dhall-haskell#2094]
## Error

In the `dhall 1.36` REPL

```dhall
⊢ { foo = 1, bar = 2 }.{ foo, foo }

Error: Invalid input

(input):1:21:
  |
1 | { foo = 1, bar = 2 }.{ foo, foo }
  |                     ^
unexpected '.'
expecting ->, :, end of input, keyword, operator, or whitespace
```

## Proposal

```
Error: Duplicate key projection

(input):1:21:
  |
1 | { foo = 1, bar = 2 }.{ foo, foo }
  |                             ^

When projecting fields, repetitions are not allowed. Please remove second occurrence of 'foo'.
```

**Comment by sjakobi** [comment]
Nice catch!

This is related to https://github.com/dhall-lang/dhall-haskell/issues/772 and https://github.com/dhall-lang/dhall-haskell/issues/1592. 

I think the best way to fix this particular issue is to store the labels of the projection in a list instead of a `Set`, and to check for duplicate fields during type checking, as required by the standard.

https://github.com/dhall-lang/dhall-haskell/blob/72026e39964cfefc81cb3cacb65bcede10eea226/dhall/src/Dhall/Syntax.hs#L610-L612

Afterwards the `Project` variant should look like this:

```
Project (Expr s a) (Either [Text] (Expr s a))

**Comment by Gabriel439** [comment]
Fix is up here: https://github.com/dhall-lang/dhall-haskell/pull/2097
