### ISSUE TITLE
Haddocks for RecordField are confusing

### ISSUE THREAD

**Issue by ocharles** [dhall-lang/dhall-haskell#2096]
The Haddocks for `RecordField` talk about comments `A`, `B` and `C`, but these aren't visible. On inspection of the source, I think the problem is they need to be escaped.

Compare https://hackage.haskell.org/package/dhall-1.36.0/docs/src/Dhall.Syntax.html#RecordField against https://hackage.haskell.org/package/dhall-1.36.0/docs/Dhall-Core.html#t:RecordField

**Comment by german1608** [comment]
This issue is not specific for `RecordField`, but for `Binding` and `FieldSelection` as well:

* https://hackage.haskell.org/package/dhall-1.36.0/docs/src/Dhall.Syntax.html#Binding
    https://hackage.haskell.org/package/dhall-1.36.0/docs/Dhall-Core.html#t:Binding
* https://hackage.haskell.org/package/dhall-1.36.0/docs/src/Dhall.Syntax.html#FieldSelection
    https://hackage.haskell.org/package/dhall-1.36.0/docs/Dhall-Core.html#t:FieldSelection

The reason is that (could be great if someone else confirms this too) Haskell's block comments can be nested, and the syntax for Dhall's block comments it's the same, so these in-between comments for documentations are erased on haddock docs.  I tried to escape those comments in the past, but no luck from my side :(

**Comment by Gabriel439** [comment]
I know how to fix this.  The trick is that if you want haddocks to render block comments in code blocks then the haddock comment itself has to use `-- ` for the comment

**Comment by Gabriel439** [comment]
Fix is up here: https://github.com/dhall-lang/dhall-haskell/pull/2098
