### ISSUE TITLE
Separating network stuff to another package

### ISSUE THREAD

**Issue by kazu-yamamoto** [dhall-lang/dhall-haskell#2107]
When I try to install a new version of `network` and `tls` (I'm a maintainer of them),  I need to remove `dhall` since it depends on them. The configuration of my HTTP server is using `dhall`. It takes much time to build the sever after reinstalling `network` or `tls` since compiling `dhall` is heavy. This is a pain.

Could you privide `Dhall.Import` from a another package such as `dhall-import`?

**Comment by sjakobi** [comment]
https://github.com/dhall-lang/dhall-haskell/issues/1102 is related. I believe `Dhall.Import` will need to be a part of the core library though, since imports are a part of Dhall's standard functionality.

What you could try is disabling `dhall`'s `with-http` Cabal flag. This removes the dependencies on `http-client`, `http-types` and `http-client-tls`, and I believe it should also remove the transitive dependencies on `network` and `tls`.

**Comment by kazu-yamamoto** [comment]
`with-http` works fine with me. Thank you for telling the flag!
