### ISSUE TITLE
Missing dhall-openapi binaries on releases for linux

### ISSUE THREAD

**Issue by muff1nman** [dhall-lang/dhall-haskell#2117]

**Comment by Gabriel439** [comment]
The main reason we don't release binaries yet is because we haven't yet uploaded `dhall-openapi` to Hackage (so it's not being formally versioned, yet, either)

**Comment by PierreR** [comment]
👍 for this. Strangely enough there is a `dhall-openapi--x86_64-macos.tar.bz2`

**Comment by muff1nman** [comment]
@PierreR I just built the binary using stack. No nix..

**Comment by denizdogan** [comment]
What is the current status of this issue? Currently when I'm running `nix-env -qa 'dhall.*'`, I get:

```
dhall-1.38.0
dhall-bash-1.0.36
dhall-docs-1.0.4
dhall-json-1.7.5
dhall-kubernetes-3.0.0-3c6d09a9409977cdde58a091d76a6d20509ca4b0
dhall-lsp-server-1.0.13
dhall-nix-1.1.20
dhall-packages-0.11.1-8d228f578fbc7bb16c04a7c9ac8c6c7d2e13d1f7
dhall-text-1.0.18
```

This is unfortunate because the two tools I really need are dhall-to-yaml-ng and dhall-openapi, but neither one of them is available via Nix? 😄  I'm on macOS, so I can install dhall-yaml using Homebrew, but it would seem to me that there is literally no way to easily access dhall-openapi without building it from source myself?

And I know that `dhall-json` contains `dhall-to-yaml`, but not `dhall-to-yaml-ng`, but then again I don't really know what the differences are, so this is all very confusing to me as a newcomer. I'm really enjoying the language so far and it has helped me immensely in setting up a new Kubernetes cluster, but it doesn't quite cut it for me if I can't generate Dhall types for lots of GKE things such as ManagedCertificate.

Is there any Slack channel dedicated to Dhall discussions? I've seen some mentions of a Dhall channel on some FP Slack, but I can't for the life of me seem to figure out how to get invited to it or if it even still exists.

**Comment by Gabriel439** [comment]
@denizdogan: What I can do is upload `dhall-openapi` to Hackage as part of the next release (which is coming up soon) and begin building binaries for it as it is starting to get reasonably stable.  That will fix the missing build of `dhall-openapi`

This `README` explains the differences between the `dhall-to-yaml` and `dhall-to-yaml-ng` executables:

* [`dhall-yaml` - `README`](https://github.com/dhall-lang/dhall-haskell/tree/master/dhall-yaml#introduction)

The short answer is that they do not differ substantially and the `dhall-to-yaml` provided by the `dhall-json` package should probably serve your needs just fine.  However, I can still explain how to install the `dhall-yaml` package since that's the only package that provides the conversion in the other direction: `yaml-to-dhall`.

You can install `dhall-to-yaml-ng` and `yaml-to-dhall` from the `dhall-yaml` package, which is available from [our release page](https://github.com/dhall-lang/dhall-haskell/releases) if you look for the archive named `dhall-yaml*` for your platform.

Also, the same `dhall-yaml` package is also available from Nixpkgs, too, but it's not packaged as a top-level statically-linked derivation.  I believe you can install it by running:

```bash
$ nix-env --install --attr haskellPackages.dhall-yaml --file '<nixpkgs>'
```

Once they package it as a top-level statically-linked derivation then you would be able to install it as:

```bash
$ nix-env --install --attr dhall-yaml --file '<nixpkgs>'
```

You can find all of the available Dhall discussion venues by checking the top-right corner of dhall-lang.org, which links to all of them.  One of those links is to the [#dhall channel of the functionalprogramming Slack](https://functionalprogramming.slack.com/app_redirect?channel=dhall).  We do not maintain a dedicated slack for Dhall and just use a channel within that Slack for now.

**Comment by denizdogan** [comment]
@Gabriel439 Thanks for all your help, much appreciated! I'm not sure if I'm doing something wrong on my part, but when I try to access the FP Slack that's linked, it looks like I already need to be a member of it. I just see a sign-in form and when I do sign in it says I don't have access to that workspace. Is it closed for new members at this time or is there some way to get invited to it? Thanks again

**Comment by Gabriel439** [comment]
@denizdogan: Double-check to verify that there's no way to register a new account.  I can't confirm on my end because I already have an account with that Slack.  If you still have difficulty then I can try to talk to the admins of the FP slack to see if they are forbidding new registrations.

**Comment by denizdogan** [comment]
@Gabriel439 I can verify that there's no sign-up link on the FP Slack page. I've verified this by checking another Slack workspace to see where the link is supposed to be (top-right corner of the page) and it's just not there for the FP Slack. This is what it is supposed to look like:

![image](https://user-images.githubusercontent.com/50928/112019564-d6e52f80-8b2f-11eb-86ca-019b45a608c2.png)

**Comment by Gabriel439** [comment]
@denizdogan: Try this: https://fpchat-invite.herokuapp.com/

… and let me know if that doesn't work

**Comment by denizdogan** [comment]
@Gabriel439 Amazing, thank you! I'm in :)

**Comment by Gabriel439** [comment]
You're welcome! 🙂

**Comment by Gabriel439** [comment]
This will be fixed by https://github.com/dhall-lang/dhall-haskell/pull/2165
