### ISSUE TITLE
Include json-to-dhall in npm package

### ISSUE THREAD

**Issue by ad-si** [dhall-lang/dhall-haskell#2177]
Sorry if this is the wrong location for that issue, but the npm package at https://www.npmjs.com/package/dhall-to-json-cli does not include the `json-to-dhall` binary. It'd be great if you could add it @somesocks!

**Comment by somesocks** [comment]
@ad-si oops, looks like I forgot to add a link to the github repo to my npm packages, you can add issues here:
https://github.com/0655-dev/dhall-cli

I split up the binaries into individual packages since they're a little large for npm packages, but I can hammer out a `json-to-dhall` npm package for you this weekend

**Comment by somesocks** [comment]
@ad-si here you go:
https://www.npmjs.com/package/json-to-dhall-cli
https://github.com/0655-dev/dhall-cli/tree/main/packages/json-to-dhall-cli

Could someone close this issue?

**Comment by ad-si** [comment]
Awesome, thanks a lot @somesocks !
