### ISSUE TITLE
dhall-format does not retain comments at end of file

### ISSUE THREAD

**Issue by esmolanka** [dhall-lang/dhall-haskell#219]
Before pretty-printing:
```
-- Before the expression

let expression = 42 in expression

-- After the expression
```

After pretty-printing:
```
-- Before the expression

let expression = 42 in expression
```

**Comment by Gabriel439** [comment]
This is a known issue.  See: https://github.com/dhall-lang/dhall-haskell/issues/145

This is because Dhall's syntax tree doesn't preserve comments, so `dhall-format` has a work-around to at least preserve them at the beginning of the file.  I could apply a similar work-around to also preserve them at the end of the file, too, but preserving them in the interior of an expression would be much more work.

**Comment by esmolanka** [comment]
Ah, I see. I tried to use `dhall-mode` for Emacs' and by default it runs `dhall-format` on save. This is how I learned that *some* comments are not retained (unlike what #145 says).

Sorry for the duplicate, then.

**Comment by Gabriel439** [comment]
No problem!
