### ISSUE TITLE
filename replaced by `(input)` for some errors

### ISSUE THREAD

**Issue by jsoref** [dhall-lang/dhall-haskell#2210]
dhall-to-json 1.7.6
### Steps / Results

```sh
echo '                                

   ./tests/fail.dhall

' | dhall-to-json


↳ ./tests/fail.dhall

Error: Invalid input

/Users/jsoref/code/validators/dhall-validator-action/tests/fail.dhall:2:1:
  |
2 | <empty line>
  | ^
unexpected end of input
expecting expression or whitespace


3│    ./tests/fail.dhall

(input):3:4
```

### Compare

```sh
echo '[env:"1"]' > missing-env.dhall
echo ./missing-env.dhall| dhall-to-json 


↳ ./missing-env.dhall
  ↳ env:"1"

Error: Missing environment variable

↳ 1

1│  env:"1"

/Users/jsoref/code/validators/dhall-validator-action/tests/missing-env.dhall:1:2
```

**Comment by basile-henry** [comment]
What do you expect it to say instead of `(input)`?

These two examples are not quite the same.

In the first case, importing `./tests/fail.dhall` fails because dhall can't parse that file. The error show the parse error for the file that was imported. And then shows where the import happens in the current input. The current input has to be named `(input)` because it comes from `stdin` and dhall has no other way to name it.

In the second case importing `./missing-env.dhall` fails but at a later stage. It was able to parse the file, it simply failed to resolve all the imports in that file. So dhall reports the importing error in that file, along with the chain of imports attempted so far.

**Comment by sjakobi** [comment]
@jsoref Note that most (all?) CLI tools in this repo support a `--file` option that you can use to provide an input file. If you use this option, you won't see `(input)` as the error location.

I'm closing this issue since it doesn't seem to show anything amiss with the tools in this repo.
