### ISSUE TITLE
Feature Request: Import env as Natural

### ISSUE THREAD

**Issue by smaccoun** [dhall-lang/dhall-haskell#2230]
I want to be able to import an environment variable as an `Integer` or `Natural`. The best example of this is having a `PORT` for an environment variable

```
  let environment = types.ListOrDict.Dict [
    {mapKey = "PORT", mapValue = appPort}
  ]
```

The issue with Text is that when i run `dhall-to-yaml`, I get quotes around the number.

I guess if there were a way for me to unsafe cast `Text` to `Natural` that would be great, but I couldn't find it

**Comment by sjakobi** [comment]
You can `env`-import values of any Dhall type, as long as the imported expression is valid, well-typed Dhall. For example:

```
≻ env FOO=3 BAR=True dhall repl
Welcome to the Dhall v1.39.0 REPL! Type :help for more information.
⊢ env:FOO

3

⊢ env:BAR

True

```

**Comment by Gabriel439** [comment]
@smaccoun: I believe in this case you can drop the `as Text` and it will do the right thing, because you can import arbitrary Dhall code via environment variables

For example:

```bash
$ PORT=22 dhall <<< 'toMap { PORT = env:PORT }'
[ { mapKey = "PORT", mapValue = 22 } ]
```

To be precise, if you drop the `as Text` then it will import the environment variable as Dhall source code (the same as file imports or URL imports), so an unsigned integer will be interpreted as a `Natural` number by default

**Comment by Gabriel439** [comment]
@sjakobi beat me to it 🙂

**Comment by smaccoun** [comment]
Wow, didn't know that. Thank you @Gabriel439  and @sjakobi for such a fast response! Will close

**Comment by Gabriel439** [comment]
You're welcome! 🙂
