### ISSUE TITLE
dhall-format breaks multi-line strings

### ISSUE THREAD

**Issue by ocharles** [dhall-lang/dhall-haskell#229]
```
[nix-shell:~/work/dhall-to-cabal]$ dhall-format <<EOF
> ''
> Hello
> World
> ''
> EOF
"Hello\nWorld\n"
```

**Comment by Gabriel439** [comment]
Yeah, this is a known issue and I would like to propose one possible solution.

I propose that `dhall-format` should not care about whether or not the original string was a multi-line or ordinary string.  Instead, it should be opinionated and decide which way to format the string based on the string contents.  The simplest possible heuristic would be: if the string has newlines, use a multi-line string literal, otherwise use an ordinary string literal.

Would that solution work for you?

**Comment by ocharles** [comment]
Sure, I think I'd be ok with that. I can't think of many (any?) scenarios where I would literally want to be typing `\n`.
