### ISSUE TITLE
Better guide for development setup?

### ISSUE THREAD

**Issue by AdamSaleh** [dhall-lang/dhall-haskell#2360]
Once in a while I try to look at Dhall and play around with the source-code,
but while the building of the packages seems to be working really well,
when I try to use doctests, or write in an IDE (like vs-code integration),
I am running into many warnigs and errors.

While I could try to complain about particular problems in my setup,
I would much rather just start from scratch and rebuild myself some sort of a blessed-setup,
where doctests will just work and I will be able to use code-completion in my IDE.

Like, I am not even set on using VS Code :-)

So, what should I use? Double down on nix-shell? Some guide I should read up on?

Thanks!

**Comment by sjakobi** [comment]
I'm also frustrated by the broken `doctest` integration with `cabal v2`. The `doctest` maintainer [recommends](https://github.com/sol/doctest/issues/326#issuecomment-997369942) using `cabal repl` to run doctests, but the incantation is so complex, I think we'd need to add a Makefile for reasonable ergonomics.

So how about we move the problematic doctest suites behind cabal flags which we can simply disable in the `cabal.project`?! In the nix and stack builds, we can keep them enabled, since they don't cause problems in these settings AFAIK. Thoughts, @Gabriel439?

What kinds of problems are you running into with VS-Code, @AdamSaleh? Are they specific to this project?

**Comment by Gabriel439** [comment]
I do all of my development inside of a `nix-shell` using Cabal's V1 commands.  So in my case this works:

```bash
$ nix-shell
$ cabal v1-test doctest
```

I also checked that `cabal v2-test doctest` also works inside of a `nix-shell`, too.

If you go the `nix-shell` route, keep in mind that you can get VS Code to work with a `nix-shell`.  I believe you want the "Nix environment selector" VS Code plugin.

**Comment by AdamSaleh** [comment]
Thanks! I have been swamped at work again, but this will definitely help me once I get some time to get back to hacking on dhall :)

**Comment by Gabriel439** [comment]
You're welcome!
