### ISSUE TITLE
dhall-format changes too much

### ISSUE THREAD

**Issue by ocharles** [dhall-lang/dhall-haskell#244]
This is gonna be a tricky one, but I think `dhall-format` does too much. The biggest annoyances for me are

1. Reordering records. In `dhall-to-cabal` the records have a "logical" flow, especially with key/value pairs. In https://github.com/ocharles/dhall-to-cabal/blob/d7ad78df7f98ba5a74bf001f3f826eb62af01a27/dhall-to-cabal.dhall#L27 I really want `name` to come first and then the `executable` to follow. Having `name` come after the `executable` unfortunate. I may introduce a function here though, to at least make that sequencing more mandatory (and remove some syntactic weight).

2. Unpredictable line breaks. The algorithm taken at the moment is one of terseness, only splitting when necessary. I think `elm-format` got things right here, though. With `elm-format`, many expressions have a single line way of formatting and a multi-line way of formatting. If you don't have a line-break, you only get the single line formatting. Introduce at least one line break and the expression will be formatted in the multi-line style, which may use many, many, more lines than just two. For Dhall, we could imagine single-line formatting for a record, and the multi-line formatting which places every field on a new line.

**Comment by Gabriel439** [comment]
(2) should be straightforward to do and is actually pretty close to how Dhall already works.  Every pretty-printed Dhall expression already has a single-line form and a multi-line form and if you run over 80 colums then the multi-line form is preferred.  Based on your description, the difference between Elm and Dhall is that Dhall independently formats the key-value pairs within a record from the record skeletone, but that's pretty easy to fix to match Elm (by having them both select single-line or multi-line form in sync with each other).

(1) is slightly trickier but still doable.  The only minor issue is that the Dhall AST doesn't preserve the order of field names since it uses a `Map` internally to store records and unions.  However, the AST could be changed (a breaking change, but I'm fine with it) to preserve the original order of field names for formatting purposes.

**Comment by ocharles** [comment]
> Based on your description, the difference between Elm and Dhall is that Dhall independently formats the key-value pairs within a record from the record skeleton, but that's pretty easy to fix to match Elm (by having them both select single-line or multi-line form in sync with each other).

More that `elm-format` does not consider line length at all. If you want to put everything on one line, you can do that. The moment you introduce a single line break, it does enough to split that expression up into multi-line form.

> However, the AST could be changed (a breaking change, but I'm fine with it) to preserve the original order

Yea, it would require a change to `dhall-haskell`s AST, but it's not an actual language change, right? That doesn't seem too bad.

**Comment by Gabriel439** [comment]
I don't think `dhall-format` can know whether or not the user inserted a line break without much more substantial changes to the AST.  Also, even then that's not the way that the `prettyprinter` library works (that `dhall-format` is based on).  `prettyprinter` just tries to format the expression in single-line form regardless of what the user originally tried to do and if the single-line form exceeds 80 columns then it uses multi-line form.

In general, I try to make `dhall-format` as "stateless" as possible meaning that it is based entirely on the syntax tree and does not care how the original file was formatted.  That's why preserving the original order of field names requires doing so in the syntax tree.  That's fine because, like you said, it's only an API change and not an actual language change.

**Comment by ocharles** [comment]
> I don't think dhall-format can know whether or not the user inserted a line break without much more substantial changes to the AST.

Don't you have SrcSpans attached to every part of the Expr? You don't need to detect line breaks, you just need to know if a SrcSpan spans multiple lines.

> Also, even then that's not the way that the prettyprinter library works (that dhall-format is based on). prettyprinter just tries to format the expression in single-line form regardless of what the user originally tried to do and if the single-line form exceeds 80 columns then it uses multi-line form.

I know exactly how prettyprinter works, but technology should not dictate user experience. If prettyprinter can't format how we want it to (which is what this conversation is really about) then prettyprinter is the wrong library to be using.

**Comment by Gabriel439** [comment]
I think that being "stateless" is the right approach, though, mainly because it's easier to reason about.  If a user wants to understand how prettyprinting works they only need to understand two orthogonal processes: how the expression is parsed into the syntax tree and how the syntax tree is rendered to a document.

If you do the pretty-printing "in one go" then it leads to more confusing semantics.  It would be like trying to mix parsing/resolution/evaluation (which is what Nix does, by the way, and it's very confusing) instead of doing them in separate phases.

**Comment by ocharles** [comment]
I'm not really understanding that comment, I'm afraid. What part of my reply does it argue against? How is my approach not stateless (it's just a function from srcspan annotated exprs to text)? Or do you mean users have to understand some internals?

**Comment by Gabriel439** [comment]
Oh, that was more of a response to the second part of your comment regarding working around `prettyprinter` limitations.

You're right that there is enough information in the syntax tree if you preserve `SrcSpans`, but then pretty-printing wouldn't work on normalized expressions because `normalize` does not preserve `Note` constructors.

**Comment by Gabriel439** [comment]
So I think for retaining field order, this may be as simple as replacing `Map` with `InsOrdHashMap`: https://hackage.haskell.org/package/insert-ordered-containers-0.2.1.0/docs/Data-HashMap-Strict-InsOrd.html

**Comment by Gabriel439** [comment]
I'll go ahead and close this since I think the two linked pull requests addressed the two original issues.  Feel free to reopen if there is still more to do here

**Comment by ocharles** [comment]
It's a good middle ground for now. I'm ok with that decision.
