### ISSUE TITLE
Question About YAML to Dhall & Dhall to YAML

### ISSUE THREAD

**Issue by buzzerpuzzle** [dhall-lang/dhall-haskell#2494]
Hi team!
I have yaml file like below.

YAML

` cmdArgs: ["/home/test.sh", "/home/test2.sh"]`
  
And I use yaml-to-dhall to get below.

DHALL

`cmdArgs = ["/home/test.sh", "/home/test2.sh"]`

However, when I like to generate YAML from DHALL and I got as below and I feel it is a little bit weird.
And curious whether I could get the way out from here.

```
cmdArgs:
  - "/home/test.sh",
  - "/home/test2.sh"
```

Thanks,
Len

**Comment by buzzerpuzzle** [comment]
Looks like its list and could be interpret either way.

**Comment by Gabriella439** [comment]
the YAML that `dhall-to-yaml` gave:

```yaml
cmdArgs:
  - "/home/test.sh",
  - "/home/test2.sh"
```

… is semantically the same as the YAML you originally started with:

```yaml
cmdArgs: ["/home/test.sh", "/home/test2.sh"]
```

… because in YAML a bulleted list is the same thing as a JSON list

`dhall-to-yaml` will prefer YAML bulleted lists when rendering YAML.  Also, keep in mind that the original formatting of your starting YAML is not recorded anywhere in the corresponding Dhall expression so when converting back to YAML it wouldn't have a way to know which version you originally intended.

**Comment by buzzerpuzzle** [comment]
I see!
Thanks for your context!

**Comment by Gabriella439** [comment]
you're welcome!!!!
