### ISSUE TITLE
Custom contexts with a "loop" loop the import resolution process

### ISSUE THREAD

**Issue by ocharles** [dhall-lang/dhall-haskell#253]
I accidentally wrote the following

```haskell
cabalContext
  :: Ctx.Context ( Expr.Expr Dhall.Parser.Src Dhall.TypeCheck.X )
cabalContext =
  let
    versionRangeType =
      Dhall.expected versionRange

  in
  Ctx.empty
    & Ctx.insert "VersionRange" versionRangeType
```

with

```haskell
versionRange :: Dhall.Type Cabal.VersionRange
versionRange =
  let
    extract =
      ..

    expected =
      Expr.Var ( Expr.V "VersionRange" 0 )

  in Dhall.Type { .. }
```

See the problem? I've essentially said that `VerisonRange` has type `Var "VersionRange"`, which seems to loop the type checker. This was super subtle and took me the best part of 15 minutes to track down, would be great if we could catch this nonsense up front.

**Comment by Gabriel439** [comment]
Yeah, this is actually a type-checking bug.  In fact, I'm pretty sure that I can turn this into a type error without using a custom context

**Comment by Gabriel439** [comment]
So, looking at this more closely:

* The Haskell implementation is (mostly) correct, meaning that there is no type-checking bug if you don't define a custom context (i.e. it relies on a certain invariant being preserved in the context)
* The standard semantics for the type-checker are actually wrong, but the Haskell implementation doesn't suffer from this issue because it doesn't exactly match the standard semantics
* There's a matching fix to both that avoids the problem that you ran into

**Comment by Gabriel439** [comment]
Actually, I take all of that back.  Both the standard semantics and the Haskell implementation appear to be correct.

However, changing things to support ill-formed custom contexts would greatly complicate the semantics so I probably won't be able to fix this issue

**Comment by ocharles** [comment]
That is unfortunately rather concerning. But I wonder if this doesn't have to go as far as the standardised semantics - could we not just do a pre-pass on the given context to ensure it has no loops?

**Comment by Gabriel439** [comment]
Also, the output schema does not need to be fully normalized.  If there are sections that share the same type, you could emit a schema that uses type synonyms to compress it

**Comment by ocharles** [comment]
Did you mean to reply to https://github.com/ocharles/dhall-to-cabal/issues/22 ?

**Comment by Gabriel439** [comment]
Oops, yes :)

**Comment by Gabriel439** [comment]
Also, the reason a pre-pass is not straightforward is because it would slow things down (you would have to verify the context validity on each variable lookup, which is one of the hot code paths of type-checking) and it's also not simple to do correctly because of Dhall's support for variable shadowing.

**Comment by ocharles** [comment]
Ok, but we could at least prepass the problem I ran into with no problems, right? That is, if `typeCheckWith` is already given a context that loops, we can at least emit a warning.

**Comment by Gabriel439** [comment]
Checking the context on each call to `typeCheckWith` would be an even larger performance penalty.  It also doesn't solve the problem that it's still very complicated to check this correctly (I tried this several times already and still failed)

**Comment by ocharles** [comment]
I have a really hard time accepting that sometimes this library will simply spin with no feedback and I have to unpick the pieces myself.

I was suggesting that any external functions that a user calls do validation once on the supplied `Context`. You could extend `Context` to have `isValid :: Bool` as a field and use laziness to both defer the check to a call site and then cache the result for subsequent calls. That means that if a user needs to pass a custom context around multiple times, the validation is at least checked only once.

An alternative is to change introduce a new `ValidContext` type that is for external entry points, and have `Dhall` use its own `Context` that does no validation.

I'm not suggesting changing internal functions and recursive calls to keep validating a context. We own the implementation there, we can simply make sure that we maintain sensible invariants as we go. Any looping from that point on is a legitimate bug in `dhall` (right? can any expressions that don't use a custom context loop? I thought the whole point of Dhall was that it was bound to terminate, and I expect that to hold for type checking).

> It also doesn't solve the problem that it's still very complicated to check this correctly

I don't (well, can't!) dispute this. The problem that I ran into though does seem like a very specific case that we could catch - entries in the `Context` cannot refer to themselves.

**Comment by Gabriel439** [comment]
So I think `isValid` would work after all.  The trick is that Dhall's well-formed contexts are automatically shifted so that any variable should not have a reference to itself.  For example, when type-checking this expression (which is legal):

```haskell
-- The polymorphic identity function with pathologically named variables
λ(a : Type) → λ(a : a) → a

-- ... which is equivalent to:
λ(a : Type) → λ(x : a) →a
```

... the context when type-checking the innermost `a` is:

```
a@1 : Type

a : a@1
```

I think rather than checking for cycles the way to do this correctly and reuse the existing type-checking semantics is to type-check each type within the context using the preceding context (with appropriate shifting).

Let me think about this some more and I will take a stab at implementing `isValid`

**Comment by ocharles** [comment]
Terrific. I do think it's worth chasing this. On the way home, I even thought that a workable middle ground could be just some kind of optional tick count to essential bound type checking time for terms. I'm not sure how that would work out, but it would at least solve the infinite spinning, and we could just dump out what we finished with (maybe something gets elaborated to `T T T T T T T T T T T ...` in which case it's fairly obvious to a human what's going on).

**Comment by Gabriel439** [comment]
Don't worry, I don't think this needs a tick count.  I am pretty sure this is just a matter of type-checking each type in the context in the right way and it will guarantee to be terminating and catch all possible type-checking loops.
