### ISSUE TITLE
trailing commas

### ISSUE THREAD

**Issue by Profpatsch** [dhall-lang/dhall-haskell#27]
If a format should be human-editable, trailing commas in lists & attrsets should be valid.
Right now it aborts with a confusing/unfitting error message:

```
→ echo "[1,2,3,]" | dhall
(stdin):1:1: error: expected: "\8704",
    "\955", "\\", "forall", "if",
    "let", "merge"
[1,2,3,] 
^        
```

```
→ echo "{foo=2,bar=4,}" | dhall
(stdin):1:1: error: expected: "[",
    "\8704", "\955", "\\", "forall",
    "if", "let", "merge"
{foo=2,bar=4,} 
^       
```

**Comment by Gabriel439** [comment]
I fixed the confusing error message with baa08c649872a058b75c71b89bc6e43c231e94b0, so you should now get these errors:

```
$ echo "[1,2,3,]" | dist/build/Dhall/dhall
(stdin):1:8: error: expected: "''",
    "(", "+", "-", "[", "\8704",
    "\955", "\\", "forall", "if",
    "let", "merge", built-in value,
    double, import, integer, label,
    list literal, natural,
    record literal, record type,
    string, union literal,
    union type
[1,2,3,]
       ^
$ echo "{foo=2,bar=4,}" | dist/build/Dhall/dhall
(stdin):1:14: error: expected: label
{foo=2,bar=4,}
             ^
```

I'll add support for trailing commas in a separate commit

**Comment by Gabriel439** [comment]
I would like to reopen this issue because I'm considering removing support for trailing commas and bars now that I'm standardizing Dhall's grammar

The two main reasons that I suggest removing them are:

*   They complicate the grammar, especially when combined with support for union literals that let you assign a value in the interior of the literal, like this:

    ```haskell
    < Foo : Integer, Bar = True, Baz : Double >
    ```

*   The new `dhall-format` utility does not make use of trailing commas or bars

Would that be alright or do you still feel that Dhall should support trailing commas and bars?

**Comment by Profpatsch** [comment]
Yeah, sure.

**Comment by Gabriel439** [comment]
Alright, thanks!
