### ISSUE TITLE
Other direction in interoperability with JSON/YAML?

### ISSUE THREAD

**Issue by deepfire** [dhall-lang/dhall-haskell#326]
In some scenarios (integrating with pre-existing code bases or different externally-imposed constraints) it is helpful to be able to import dumb data from existing JSON / YAML files.

Is this even theoretically possible to fit in the Dhall model?

Perhaps if we could specify a type signature at the "foreign import" boundary?

Would it then have to be a language builtin?

**Comment by Gabriel439** [comment]
Yes, this can fit within the Dhall model.  For example, Dhall already supports an `as Text` modifier to imports to import raw `Text` and could conceivably have an `as JSON` modifier, too, like this:

```haskell
./foo.json as JSON : List { name : Text, age : Natural }
```

The main reason I haven't done this so far is because most JSON in the wild is weakly typed due to either omitting fields from records:

```json
[ { "x": 1 }, { "x": 2, "y": "foo" } ]
```

... or using values of entirely different types in a list:

```json
[ 1, "foo" ]
```

Dhall could be strict and only accept a subset of JSON that was well-typed, but I wasn't sure how useful that would be.

**Comment by cleverca22** [comment]
main use i was thinking of, is to have some constants that are shared between other tools that can only read JSON, so it would just be something simple like `{ "version":"1.2.3" }` and it must always have a string in the `version` field

**Comment by aleator** [comment]
I would like to point out that `as CSV` could also be considered, since CSV files are usually more regular than JSON/YAML. This would also allow an indirect path from JSON using csvkit's `incsv` command.

Furthermore, there are always those nasty exel files floating around...

**Comment by Gabriel439** [comment]
I will migrate this issue to the https://github.com/dhall-lang/dhall-lang/ repository since this is more of a question about the language specification than the Haskell implementation.  I opened a new issue here to centralize discussion on this feature:

https://github.com/dhall-lang/dhall-lang/issues/121
