### ISSUE TITLE
String -> Dhall.Text

### ISSUE THREAD

**Issue by FintanH** [dhall-lang/dhall-haskell#341]
I have a scenario where I want to get my root folder where my Dhall files live during testing. Something like:

```haskell
spec :: Spec
spec = do
  mRoot <- runIO $ lookupEnv "ROOT_DHALL"
  root  <- maybe (error "ROOT_DHALL was not set") (pack . pure) mRoot

  detailed "Dhall to Haskell" $ do
    it "works!" $ do
      res <- input auto $ root <> "myDhallType"
      p `shouldBe` MyDhallType
```

But from what I can see this `pack` function or something equivalent doesn't exist. Am I missing how to do this or does it need to be added?

**Comment by FintanH** [comment]
Closing upon realising `Text` in `Dhall` is `Data.Text.Lazy.Text` 😅

**Comment by Gabriel439** [comment]
No problem! :)

**Comment by ocharles** [comment]
I actually find Dhall re-exporting `Text` to be confusing, mostly because there's no indication in the documentation that it's Lazy text (other than *very* subtle hint on the `Pretty` instance for it). I'm not sure that re-export is buying us much.

FintanH's confusion suggests I'm not the only one who has found it confusing.

**Comment by Gabriel439** [comment]
So back when I added the re-exports, the main rationale for doing so was to promote people using the types that would be the most efficient to marshal across the Dhall-Haskell boundary (i.e. the types that match the internal representation)

Things have changed since then (for example, `ListLit`s are now backed by `Seq` instead of `Vector` and `DoubleLit`s are now backed by `Scientific`), but I still think there is value in a convenient module that exports all the relevant functionality one needs to get going for small projects.  It doesn't necessarily have to be the `Dhall` module but I think there should be some module for that purpose.

What I really want to avoid is people marshaling Dhall `TextLit`s into `String`s because they are too lazy to add a `text` dependency and a `Data.Text` import to their module.  That would be the worst outcome in my opinion.
