### ISSUE TITLE
Optimization opportunities during normalization

### ISSUE THREAD

**Issue by sjakobi** [dhall-lang/dhall-haskell#365]
It seems to me that for the following combinations of functions, normalization could take shortcuts:

* `List/head` & `List/build`
* `List/head` & `List/append`
* `List/last` & `List/build`
* `List/last` & `List/append`
* `List/fold` & `List/build`
* `List/indexed` & `List/build`
* `Natural/fold` & `Natural/build`
* `Optional/fold` & `Optional/build`

For the `fold` & `build` combinations, the reverse cases of `build` using `fold` already fuse. The more "classical" list fusion looks like it could be implemented too.

**Comment by sjakobi** [comment]
Not sure if these are worth considering though as they all seem to require a change in semantics?!

**Comment by Gabriel439** [comment]
Actually, we could partially take advantage of this even without a change in semantics.  These rules only require a change in semantics when they are applied to an abstract list, i.e.:

```
λ(a : Type) → λ(xs : List Integer) → List/head Integer (xs # [1, 2, 3])
```

... but if you apply them to a non-abstract list then you could optimize the operation without any change to the semantics, i.e.:

```
List/head Integer ([1, 2, 3] # [4, 5, 6])
```

... could be optimized to run in O(1) time since the result is still the same.  The standard specifies that an implementation is free to take any route to get to the final result as long as the result is still the same.  For example, `Natural/even` and `Natural/odd` are specified very inefficiently in the semantics and are actually implemented using efficient machine operations in the Haskell implementations.

However, that's still not an entirely satisfactory solution because very often we want to distribute reusable utilities (like `Prelude/List/replicate`) precisely because most people don't want to program directly using `List/fold` and `List/build`.  If you normalize those utilities first to find fusion opportunities then all occurrences of `List/build` would disappear since according to the current semantics it is never in normal form (mainly to ensure that normalization is confluent).

That said, I think your proposal is definitely worth doing (even for operating on abstract lists), but if we do so then we need to make sure that normalization is still confluent as a result of such a change in semantics.

**Comment by sjakobi** [comment]
Closing, since fusion was abandoned in https://github.com/dhall-lang/dhall-lang/pull/792.
