### ISSUE TITLE
How to import a path from Text variable?

### ISSUE THREAD

**Issue by w3rs** [dhall-lang/dhall-haskell#380]
I can't figure out how can I bind a directory path to a variable and then create imported paths with it. Is it possible at all? E.g. something like this:

```
let dir = "${env:HOME as Text}/config" in
let myType = dir/someType in
let myLib = dir/someLib in
...
```

**Comment by ocharles** [comment]
I don't believe this is possible, as it could be a security risk.

**Comment by w3rs** [comment]
Hmm, it's a bit unfortunate, given that I can't combine types and values in a single record (right?). E.g. if I want to import both Monoid and something else from the Prelude, i'd need to specify the path twice:

let Prelude = PATH_TO_PRELUDE/Prelude/package.dhall in
let Monoid = PATH_TO_PRELUDE/Prelude/Monoid in
...

For files, I can use symlinks, but for URLs I'm not sure what how to avoid repetition.

**Comment by ocharles** [comment]
I believe you're entirely correct in all those points, including it being unfortunate :upside_down_face:

**Comment by Gabriel439** [comment]
Yeah, you will have to specify the path twice (both for file paths and URLs).  Dhall does not support computed imports

The main reason why Dhall does not support computed imports is because import resolution strictly precedes both type-checking and normalization.  In order to resolve your original example, Dhall would have to normalize the file to replace all references to `dir` with `"${env:HOME as Text}/config", but you can't normalize the file unless you type-check the file first (otherwise normalization might diverge), but you can't type-check the file if there are unresolved imports, leading to a chicken-and-egg problem.

There is also the security reason that @ocharles mentioned, which is that for URL imports this can be used to exfiltrate sensitive data stored in environment variables.  For more details, see:

https://github.com/dhall-lang/dhall-lang/wiki/Safety-guarantees

However, the phase separation issue is the more important reason why this is not supported.

**Comment by ocharles** [comment]
I think Gabriel's answer clarifies why this isn't supported, and more importantly why it *can't* be supported. I'll close this, but if you think that's in error just shout and we can re-open this and continue the conversation.
