### ISSUE TITLE
Ambiguous integrity checking with 'using' keyword.

### ISSUE THREAD

**Issue by foollbar** [dhall-lang/dhall-haskell#441]
meaning of semantic integrity is clear without 'using' keyword.

Input:

<pre>
https://raw.githubusercontent.com/dhall-lang/Prelude/c79c2bc3c46f129cc5b6d594ce298a381bcae92c/List/replicate sha256:b0e3ec1797b32c80c0bcb7e8254b08c7e9e35e75e6b410c7ac21477ab90167ad
</pre>

Output:

<pre>∀(n : Natural) → ∀(a : Type) → ∀(x : a) → List a

  λ(n : Natural)
→ λ(a : Type)
→ λ(x : a)
→ Natural/fold n (List a) (λ(`as` : List a) → [ x ] # `as`) ([] : List a)</pre>

but Dhall compares annotated hash with ./a.dhall's hash, not the imported expression's hash.

a.dhall
<pre>
[{header="1", value="2"}]
</pre>

Input:

<pre>
https://raw.githubusercontent.com/dhall-lang/Prelude/c79c2bc3c46f129cc5b6d594ce298a381bcae92c/List/replicate using ./a.dhall sha256:b0e3ec1797b32c80c0bcb7e8254b08c7e9e35e75e6b410c7ac21477ab90167ad
</pre>

Output:

<pre>
Error: Import integrity check failed

Expected hash:

↳ b0e3ec1797b32c80c0bcb7e8254b08c7e9e35e75e6b410c7ac21477ab90167ad

Actual hash:

↳ 16173e984d35ee3ffd8b6b79167df89480e67d1cd03ea5d0fc93689e4d928e61
</pre>

there is no way to check integrity of imported expression's semantic which comes with 'using' keyword at this moment, and i doubt that it is an intended behavior.

**Comment by Gabriel439** [comment]
Yeah, this looks like this is an ambiguity in the grammar.  According to the grammar, this expression:

```haskell
https://raw.githubusercontent.com/.../replicate using ./a.dhall sha256:...
```

... could be interpreted like this:

```haskell
https://raw.githubusercontent.com/.../replicate using (./a.dhall sha256:...)
```

... or like this:

```haskell
(https://raw.githubusercontent.com/.../replicate using ./a.dhall) sha256:...
```

What you want is the latter interpretation (which I agree should be the default interpretation) but the Haskell implementation is using the former interpretation and there is no workaround for that at the moment since the grammar currently does not permit the use of explicit parentheses to disambiguate the two.

One solution might be to change the grammar to permit optional parentheses around the headers import, like this:

```abnf
http = http-raw whitespace [ using (import-hashed / open-parens import-hashed close-parens) ]
```

... which would be backwards-compatible with existing code while still permitting the use of explicit parentheses to disambiguate which import the hash belongs to.  Then you could unambiguously attach the hash to the main import like this:

```haskell
https://raw.githubusercontent.com/dhall-lang/Prelude/c79c2bc3c46f129cc5b6d594ce298a381bcae92c/List/replicate using (./a.dhall) sha256:b0e3ec1797b32c80c0bcb7e8254b08c7e9e35e75e6b410c7ac21477ab90167ad
```

... or attach the hash to the header import like this:

```haskell
https://raw.githubusercontent.com/dhall-lang/Prelude/c79c2bc3c46f129cc5b6d594ce298a381bcae92c/List/replicate using (./a.dhall sha256:16173e984d35ee3ffd8b6b79167df89480e67d1cd03ea5d0fc93689e4d928e61)
```

Would that work for you?

**Comment by foollbar** [comment]
It looks great to me. for clarity, does changes makes following code valid?<pre>https://raw.githubusercontent.com/dhall-lang/Prelude/c79c2bc3c46f129cc5b6d594ce298a381bcae92c/List/replicate using (./a.dhall sha256:16173e984d35ee3ffd8b6b79167df89480e67d1cd03ea5d0fc93689e4d928e61) sha256:b0e3ec1797b32c80c0bcb7e8254b08c7e9e35e75e6b410c7ac21477ab90167ad</pre>

And I think that modification of the default interpretation of Haskell implementation would be preferable.

**Comment by Gabriel439** [comment]
@foollbar: Yes, that would be valid.

What I think I will probably do is eventually deprecate and remove the version without the parentheses so that there is no ambiguous representation.  Fixing the Haskell implementation to prioritize one interpretation over another wouldn't fix the root problem which is that the grammar is ambiguous and the specification shouldn't rely on implementation-defined behavior.

**Comment by Gabriel439** [comment]
Proposed change to the grammar here: https://github.com/dhall-lang/dhall-lang/pull/171
