### ISSUE TITLE
`dhall-format` removes parens around record access in URIs

### ISSUE THREAD

**Issue by FintanH** [dhall-lang/dhall-haskell#453]
Discovered with `HEAD`

Minimal example:
* Two files `testImport`, `test`

testImport
```
{ hello = "Hello" }
```

test
```
./testImport .hello
```

```
Error: Invalid input

/Users/halpenny/Developer/dhall-haskell/test:1:15:
  |
1 | ./testImport .hello
  |               ^
unexpected 'h'
expecting '/'
```

You can fix this by doing `(./testImport).hello` but `dhall-format` will remove the parentheses.

**Comment by Gabriel439** [comment]
@FintanH: I found the problem.  The root cause is that `dhall-format` is wrong and shouldn't be removing the parentheses that you add.

There was a recent change to the grammar in https://github.com/dhall-lang/dhall-lang/pull/161 that makes parentheses mandatory around imports when accessing a field in order to avoid ambiguity and `dhall-format` just needs to be updated to match the new grammar

**Comment by FintanH** [comment]
Alrighty! I'll change the title to reflect the actual issue.

**Comment by Gabriel439** [comment]
Fix up in https://github.com/dhall-lang/dhall-haskell/pull/471
