### ISSUE TITLE
Record formatting should be ordered by key

### ISSUE THREAD

**Issue by justinwoo** [dhall-lang/dhall-haskell#518]
While previously changed with #244, insertion order being preserved has made for looking at diffs of Dhall files even harder for me, especially when working with records with many fields.

Since users can define functions to require arguments in a specific order to build records, is there a need to  preserve this information and force it for formatting?

Related to https://github.com/dhall-lang/dhall-json/issues/33

**Comment by Gabriel439** [comment]
I think whether or not record fields are ordered is orthogonal to whether or not curried function arguments are ordered.  For example, you can transform any curried function like this:

```haskell
  λ(x : Text)
→ λ(y : Text)
→ { foo = "${x} ${y}"
  , bar = "${y} ${x}"
  }
```

... into a function that accepts a record of arguments instead:

```haskell
  λ(r : { x : Text, y : Text })
→ { foo = "${r.x} ${r.y}"
  , bar = "${r.y} ${r.x}"
  }
```

... and that record that you supply as input to the function can have the fields defined in any order.

It's also not clear to me why preserving the original order of fields affects the ability to `diff` files.  If anything, I would expect preserving the original order to make diffs smaller.

Also, there is no need to use the `diff` Unix command to compare two Dhall files.  Newer versions of `dhall` provide the `dhall diff` subcommand which lets you compare two arbitrary Dhall expressions, and that `diff` subcommand is order-insensitive:

```
$ dhall diff '{ x = 1, y = 2 }' '{ y = 2, x = 1 }'
{ …
}

$ dhall diff '{ x = 1, y = 2 }' '{ y = 2, x = 1, z = 3 }'
{ + z = …
, …
}
```

I also think it is a good thing that the interpreter preserves the original order since sometimes an order other than alphabetical order might be clearer to read when examining the configuration file and I wouldn't want the automatic formatting to clobber that information.

**Comment by f-f** [comment]
How about adding a `--sort` flag to `dhall format`?

**Comment by sellout** [comment]
@f-f I would prefer a flag like `--discard-field-order` or something, only because the phrasing of “sort” makes it sound like Dhall is doing extra work, rather than less.

The performance impact of InsOrdHashMap is significant, and I would _love_ to be able to turn it off in places where humans are not the target of the output.

**Comment by Gabriel439** [comment]
It's still not clear to me what is the use case for sorting the fields

**Comment by sellout** [comment]
For me, just performance. I forget the numbers, but it was significantly faster when I had a branch that didn’t use InsOrdHashMap.

Actually, what I had wanted to propose at the time was to abstract over a record of map operations, and `dhall` could implement it with `InsOrdHashMap`, and I would use a different `Map` in my Haskell code. I don’t think I need the application itself to add sorting.

**Comment by joneshf** [comment]
If we're talking "always sort alphabetically and never retain insertion order," we could drop the dependency on `lens`. End users of the dhall binary aren't really affected by it. Anybody using `dhall` as a dependency is. That dependency on `lens` sometimes is the difference between CI building or timing out (depending on CI and time limits).

**Comment by Gabriel439** [comment]
@joneshf @sellout: If performance and dependencies are the issue, maybe we can use a simpler internal replacement to `InsOrdHashMap` that is just `Data.Map` + a list of the original keys in order

**Comment by Gabriel439** [comment]
Also, I just want to note here that we did end up switching to an internal `Map` implementation in #612, which fixes two of the issues mentioned in this thread:

* We've removed the dependency on `lens`
* The performance improved compared to `insert-ordered-containers`

Given that I believe the original use case is already addressed by the `dhall diff` subcommand I'm going to close.  However, feel free to reopen if there are additional concerns about diffing Dhall expressions.
