### ISSUE TITLE
parsing identifier which name starts with reserved keyword

### ISSUE THREAD

**Issue by semio** [dhall-lang/dhall-haskell#547]
Dhall fails to parse identifier when the identifier's name starts with a reserved keyword, for example: 

```bash
➔ dhall <<< "let mergedRec = { a = 1 } // { b = 2 } in mergedRec"

Error: Invalid input

(stdin):2:1:
  |
2 | <empty line>
  | ^
unexpected end of input
expecting "!=", "&&", "++", "->", "//", "//\\", "/\", "==", "||", "→", "∧", "⩓", "⫽", '#', '(', '*', '+', '.', '?', '@', built-in expression, double literal, import, integer literal, label, list literal, natural literal, record type or literal, text literal, the rest of label, or union type or literal
```

But it works if I rename the variable name

```bash
➔ dhall <<< "let _mergedRec = { a = 1 } // { b = 2 } in _mergedRec"
{ b = 2, a = 1 }
```

Also I found `dhall format` gives incorrect result when the identifier starts with `constructors`:

```bash
➔ dhall format <<< "let constructorsRec = { a = 1, b = 2 } in constructorsRec"
let constructorsRec = { a = 1, b = 2 } in constructors Rec    
##                                                    ^ a space was inserted
```

**Comment by ocharles** [comment]
But isn't `True` a reserved keyword? The file that is just `True<EOF>` should parse, so I guess "non-empty whitespace" can also be EOF?

**Comment by Gabriel439** [comment]
Oh yeah, good point.  Let me think more about this

**Comment by Gabriel439** [comment]
Here's another idea: we can require non-empty whitespace after the following key words since they cannot be followed by end-of-file:

* `if`
* `then`
* `else`
* `let`
* `in`
* `as`
* `using`
* `merge`
* `constructors`

This appears to work because all of the remaining reserved identifiers are built-in functions and values which don't exhibit this problem because the grammar already correctly supports identifiers that begin with built-in names thanks to https://github.com/dhall-lang/dhall-lang/pull/122

    ```
    $ dhall <<< 'let Truex = 1 in Truex'
    Natural

    1
    $ dhall <<< 'let Natural/foldx = 1 in Natural/foldx'
    Natural

    1
    ```

I will propose that tomorrow if nobody has any objections

Also, cc: @f-f since I know he is interested in removing ambiguities from the grammar

**Comment by f-f** [comment]
@Gabriel439 yeah, I think that is the right solution 👍 Would it break anything? (any valid expression, that is)

**Comment by Gabriel439** [comment]
@f-f: Yes, it would break expressions like these:

```haskell
if(True) then 1 else 2
```

```haskell
merge{ x = λ(_ : {}) → 1 } < x = {=} >
```

**Comment by Gabriel439** [comment]
Here is the proposed change to the standard grammar: https://github.com/dhall-lang/dhall-lang/pull/222

**Comment by Gabriel439** [comment]
Here's the matching change to the Haskell implementation: https://github.com/dhall-lang/dhall-haskell/pull/551
