### ISSUE TITLE
Semantic integrity hash affected by field order

### ISSUE THREAD

**Issue by joneshf** [dhall-lang/dhall-haskell#548]
It looks like something changed to the way hashes work for records and unions. In an older version, the order of fields in records/unions would not change the hash. That seems to be [in line with the standard](https://github.com/dhall-lang/dhall-lang/blob/master/standard/semantics.md#records-1). In more recent versions, the order of fields affects the hash produced.

<details>
<summary>dhall-hash 1.8.2</summary>

```
[nix-shell:~]$ dhall --version
1.8.2

[nix-shell:~]$ echo '{foo = 1, bar = 2}' | dhall-hash
sha256:6364e21a806e13b82afaa6ea927ae23e15bb53da2573292f085911396877cf3f

[nix-shell:~]$ echo '{bar = 2, foo = 1}' | dhall-hash
sha256:6364e21a806e13b82afaa6ea927ae23e15bb53da2573292f085911396877cf3f

[nix-shell:~]$ echo '<foo : Natural | bar : Natural>' | dhall-hash
sha256:657b73e8d23f4386ba6895247a6dda9c762c4beb35e6e8a3b0108d6d3888b91c

[nix-shell:~]$ echo '<bar : Natural | foo : Natural>' | dhall-hash
sha256:657b73e8d23f4386ba6895247a6dda9c762c4beb35e6e8a3b0108d6d3888b91c
```
</details>

<details>
<summary>dhall hash 1.16.1</summary>

```
$ echo '{foo = 1, bar = 2}' | stack exec dhall -- hash
sha256:83f262b95390c2c55b381d753802019bb3188a25ac5fbe3c8b3c00c47afd9534
$ echo '{bar = 2, foo = 1}' | stack exec dhall -- hash
sha256:6364e21a806e13b82afaa6ea927ae23e15bb53da2573292f085911396877cf3f
$ echo '<foo : Natural | bar : Natural>' | stack exec dhall -- hash
sha256:d188708d41b0db2981e50442bdd19ace258830e9e13fd1a3b6ec94b2224d8578
$ echo '<bar : Natural | foo : Natural>' | stack exec dhall -- hash
sha256:657b73e8d23f4386ba6895247a6dda9c762c4beb35e6e8a3b0108d6d3888b91c
```
</details>

Is this change intended? If so, we should update the spec to make that clearer.

**Comment by Gabriel439** [comment]
Thinking about this more, what I plan to do is to have the specification only require that β-normalization sorts fields, since that would in turn guarantee that semantic integrity checks sort fields (since a semantic integrity check is done post-αβ-normalization).

The reason for doing things this way is that binary encoding could in principle be used for things other than semantic integrity checks (i.e. perhaps you want to serialize an expression that has not been normalized and you want to preserve identifier names and field order).  By specifying that normalization is required as part of β-normalization but not required as part of binary serialization we can preserve the ability to opt out of normalization when encoding expressions for alternate use cases.  This is the same reason that binary serialization is specified for `let` expressions and imports even though they will never appear in a fully resolved and normalized expression.

**Comment by Gabriel439** [comment]
Here's the matching change to the Haskell implementation: https://github.com/dhall-lang/dhall-haskell/pull/552

**Comment by joneshf** [comment]
Wooo! Thanks for the quick fixes!

**Comment by Gabriel439** [comment]
@joneshf: You're welcome! :slightly_smiling_face:
