### ISSUE TITLE
Make tests more language-agnostic

### ISSUE THREAD

**Issue by f-f** [dhall-lang/dhall-haskell#568]
I'd love to to possibly reuse *all* the tests from this implementation in [dhall-clj](https://github.com/f-f/dhall-clj), and in the end have a kind-of-agnostic shared test-suite to validate implementations on.
(current status: I'm using all the normalization an typecheck tests, and it's working great)

If this sounds like a good idea, I would like to:
- contribute new tests here ([I'm monitoring the test coverage](https://coveralls.io/github/f-f/dhall-clj?branch=master), and some places - e.g. the typechecker - are a bit uncovered). 
  Related: should we track coverage also here?
- adapt the current tests to be more agnostic. This includes stuff like:
  - applying existing conventions all over, like in #567
  - move tests from Haskell source to Dhall files - I noticed some tests check against an AST built in code instead of parsing it from source
  - make existing tests more precise: e.g. the `parser` tests are either "parse" or "not parse", while it would be helpful to apply the  `A/B` convention and have a "correct" parse to check against.
    A possible way to do this would be to: dump the AST to file as outputted by the Haskell implementation to the `B` files, and use it in the Haskell tests by `read`ing it. Then other implementations can "parse" this AST (it's basically a lisp, acceptably easy to parse IMO) and reuse it.

**Comment by joneshf** [comment]
> move tests from Haskell source to Dhall files - I noticed some tests check against an AST built in code instead of parsing it from source

If you mean stuff like: https://github.com/dhall-lang/dhall-haskell/blob/b5c005ee2bd83f40deaec52e8a472c876d9db572/tests/Normalization.hs#L208-L231

I think that's checking contexts in Haskell. I think `simpleCustomization` is validating normalization for a single addition to the context. I think `nestedReduction` is validating normalization can "see through" multiple additions to the context. Assuming that's a correct interpretation, is there a way to check the spirit of those tests without using the host language (Haskell)?

I think what these tests are showing is that there are different categories of testing happening (sometimes in the same file). Maybe more changes like you did in #567 can help flesh out the categories.

**Comment by Gabriel439** [comment]
I think the language-agnostic test files should probably be relocated to the `dhall-lang` repository since those can be viewed as part of the standard since they are conformance tests.  The exception would be test files for features that have not been standardized (like formatting code)

Most of the tests that are implemented in Haskell are due to them exercising non-standard features of the Haskell API (like adding new built-in functions).  Those will probably have to stay as Haskell code due to them being specific to the Haskell API and not relevant to the standard.

For parsing code I don't think we should mandate what abstract syntax tree that the concrete syntax gets parsed into, mainly because it's not a user-visible feature so an implementation should be free to use a non-standard representation internally as long as it is still externally standards compliant.  For example: parsing `[ x  ] : List a` as `Annot (ListLit Nothing [ x ]) (App List a)` instead of `ListLit (Just a) [ x ])`.  This is similar to how the specification says that an implementation can freely implement various β-normalization rules in a more efficient way.

In general, if there are sections if the grammar that we think are at risk of being parsed ambiguously we should be able to come up with appropriate test cases to exercise those corners of the grammar (for example: `a./a` or `sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa`)

Also, this reminded me to add coverage checking to Dhall: https://github.com/dhall-lang/dhall-haskell/pull/569

**Comment by f-f** [comment]
@Gabriel439 
+1 on moving the agnostic tests to `dhall-lang`

> For parsing code I don't think we should mandate what abstract syntax tree that the concrete syntax gets parsed into, mainly because it's not a user-visible feature so an implementation should be free to use a non-standard representation internally as long as it is still externally standards compliant.

Right, I didn't consider that would mean standardizing the AST.
Some further options:
- We could have the tests there, but mark the AST as "non-prescriptive". 
  Nothing else would depend on its format, and in general transforming it to a different AST should not be a big task (e.g. in your example it is easy to transform from `Annot (ListLit Nothing [ x ]) (App List a)` to `ListLit (Just a) [ x ])` and viceversa).
  In my case I have a slightly different AST, but I'd be fine with parsing and transforming it to run some tests, as "some tests" is much better than "no tests"
- We could leave the parsing tests in this repo, but still dump the ASTs to file and version them here.
  In this way they would be nowhere near the standard, but still more accessible for anyone willing to tolerate breakage due to relying on the internal representation :)

**Comment by f-f** [comment]
As we agreed above, we should move the conformance tests (so far they are `normalization` and `typecheck` tests) to the `dhall-lang` repo.  
Since they import the Prelude through local imports, we'll have to:
- add the Prelude as submodule in `dhall-lang`
- add `dhall-lang` as submodule of this repo

We cannot have submodules in here yet (see #581), so we should fix that before proceeding with moving the tests.

**Comment by f-f** [comment]
About a possibly not-agnostic test in the `normalization` suite:

[This expression](https://github.com/dhall-lang/dhall-haskell/blob/master/tests/normalization/examples/Natural/fold/1A.dhall) is supposed to be normalized to [this one](https://github.com/dhall-lang/dhall-haskell/blob/master/tests/normalization/examples/Natural/fold/1B.dhall):
```haskell
λ(zero : Natural) → 5 * 5 * 5 * zero
```

However, my implementation normalizes it to:
```haskell
λ(zero : Natural) → 125 * zero
```

...which is clearly equivalent.

Now, this comes from the fact that this implementation sometimes has strict folding and [sometimes lazy folding](https://github.com/dhall-lang/dhall-haskell/blob/master/src/Dhall/Core.hs#L1451), while in mine I always go strict (can this lead to incorrect results? If yes, we should add a test for it).
AFAIK the standard doesn't mention anything about it, but I feel it probably should (so we get only one possible normal form)

/cc @Gabriel439

**Comment by Gabriel439** [comment]
@f-f: Actually, the issue here is that the standard doesn't specify whether the operators are left- or right-associative when they are not explicitly parenthesized.

The reason that the Haskell implementation is returning `5 * 5 * 5 * zero` is because it is parsed as:

```
5 * (5 * (5 * zero))
```

... whereas the Clojure implementation is (I'm guessing) parsing it as:

```
((5 * 5) * 5) * zero
```

... and only the latter form simplifies to `125 * zero`.

I think this can be fixed by just adding a note to the grammar specifying the default associativity.

My guess is that left associativity (i.e. what the Clojure implementation appears to be doing) is probably the better default because it's more efficient for an LALR parser to implement, and it's not hard to make a recursive-descent parser accomodate it (by parsing it as a right-associative linked list and then flipping the associativity using `foldl`)

**Comment by f-f** [comment]
@Gabriel439 you're right, this is the AST I get from the parse:
```clojure
#dhall_clj.ast.Lam
{:arg "zero",
 :body #dhall_clj.ast.NaturalTimes
 {:a #dhall_clj.ast.NaturalTimes
  {:a #dhall_clj.ast.NaturalTimes
   {:a #dhall_clj.ast.NaturalLit {:n 5}, :b #dhall_clj.ast.NaturalLit {:n 5}},
   :b #dhall_clj.ast.NaturalLit {:n 5}},
  :b #dhall_clj.ast.Var {:i 0, :x "zero"}},
 :type #dhall_clj.ast.NaturalT {}}
```

+1 for left associativity by default.

I just realized I assumed everything was left-associative (as function application is left associative in the haskell implementation, though now I'm not sure anymore if I read anything relevant in the standard)

**Comment by Gabriel439** [comment]
@f-f: In the case of function application it is definitely supposed to be left-associative, just like in Haskell

**Comment by f-f** [comment]
@Gabriel439 Re: making the `parser` tests agnostic: we figured that having AST there would not be good as it's not part of the standard, but how about using the JSON representation of CBOR as a "reasonably close AST representation"?  

That is, `A` would be an expression to parse (e.g. `λ(x : Bool) → x`), and `B` would be  its CBOR representation (in plaintext JSON - for readability) - in this case `[1, "x", "Bool", "x"]`

This still accomplishes the goal of "testing that parsing this thing gives you what you should expect", it's reasonably small to implement (one has to read JSON and convert from our CBOR encoding) and has the advantage that it also tests said CBOR decoding (which one had to do anyways)

**Comment by Gabriel439** [comment]
@f-f: Yeah, that seems fine to me, since it's reusing something we've already standardized and CBOR is an unambiguous representation
