### ISSUE TITLE
deprecate constructors

### ISSUE THREAD

**Issue by FintanH** [dhall-lang/dhall-haskell#635]
Making an issue to mirror https://github.com/dhall-lang/dhall-lang/issues/244

I'm currently trying to tackle it right now and I'm running into a bit of a wall with understanding what I need to change. @Gabriel439 is there a workflow of how to update a change in the core language that you work by? For example, change `Parser` -> `TypeChecker` -> `Normalizer`. Or do you have some jumping off points for me to look at?

Thanks!

**Comment by Gabriel439** [comment]
@FintanH: In general I recommend trying to start with a change to the standard first before the Haskell implementation.

However, for both the standard and the Haskell implementation the main changes for each phase would be:

Phase 1: Overload the behavior of `.`

*   Change the type-checker (i.e. `Dhall.TypeCheck.typeWith` to add a new case for inferring the type of an expression using `Field` where the first argument is a concrete union type

    It will be similar to the implementation of the `Constructors` case of the same `typeWith` function, except that instead of computing the type of the whole constructors record you just compute the type of one constructor

*   Change the normalizer (i.e. `Dhall.Core.{normalizeWith,isNormalized}`) to also add another case for normalizing `Field` where the first argument is a concrete union type

    This will also be similar to the implementation of the `Constructors` case of the `normalizeWith` function except that instead of computing the logic for assembling a record of all the constructors you just assemble one of them

Phase 2: Change the behavior of `constructors` so that `constructors x = x`

* Change the type-checker so that the type of `constructors x` is the same as the type of `x`
* Change the normalizer so that normalizing `constructors x` is the same as normalizing `x`

Phase 3: Remove `constructors`

* Just delete `Constructors` from the `Expr` type and fix all the error messages :)

To answer your more general question, if a feature touches every aspect of the interpreter then the usual thing I do is just add a new constructor to the `Expr` type and just fix all the non-exhaustive pattern match warnings until the program works.

**Comment by jneira** [comment]
Wow, imo that comment deserves to be in a relevant place

**Comment by FintanH** [comment]
Thanks @Gabriel439! It makes sense that you'd change the standard first, but I'd like to battle test the implementation to see if this would help our use case first :)

I was starting what you mentioned, but was running into some issues. I'll see if I can figure out what's going on.

**Comment by Gabriel439** [comment]
I will go ahead and close this since https://github.com/dhall-lang/dhall-lang/issues/244 supersed this issue
