### ISSUE TITLE
warning: treating <U+2227> as identifier character

### ISSUE THREAD

**Issue by philderbeast** [dhall-lang/dhall-haskell#646]
Is this warning harmless?

```
dhall-haskell> stack repl

Warning: There were multiple candidates for the Cabal entry " Dhall.Main
         * /.../dhall-haskell/Dhall/Main.hs
         picking: /.../dhall-haskell/src/Dhall/Main.hs

Warning: There were multiple candidates for the Cabal entry " Dhall.Main
         * /.../dhall-haskell/Dhall/Main.hs
         picking: /.../dhall-haskell/src/Dhall/Main.hs

Warning: There were multiple candidates for the Cabal entry " Dhall.Main
         * /.../dhall-haskell/Dhall/Main.hs
         picking: /.../dhall-haskell/src/Dhall/Main.hs
Configuring GHCi with the following packages: dhall
Using main module: 1. Package `dhall' component exe:dhall
with main-is file: /.../dhall-haskell/dhall/Main.hs
GHCi, version 8.4.3: http://www.haskell.org/ghc/  :? for help
Loaded GHCi configuration from /Users/pdejoux/.ghci

/.../dhall-haskell/src/Dhall/Core.hs:435:58: error:
     warning: treating Unicode character <U+2227> as identifier character
rather than as '^' symbol [-Wunicode-homoglyph]
        -- | > Combine x y                              ~  x ∧ y
                                                             ^
    |
435 |     -- | > Combine x y                              ~  x ∧ y
    |
```

**Comment by philderbeast** [comment]
I logged a [ticket](https://ghc.haskell.org/trac/ghc/ticket/15775#ticket) about this with ghc.

**Comment by Gabriel439** [comment]
Thanks for doing that! 🙂

**Comment by mattpolzin** [comment]
Not sure whether to resurrect this ticket, but since it is clearly an extension of the same conversation, I tried to build via Nix and saw the same warnings (albeit in different files) as errors.

For example:
```
src/Dhall/Tutorial.hs:889:31: error:
     error: treating Unicode character <U+2227> as identifier character rather than as '^' symbol [-Werror,-Wunicode-homoglyph]
    |
889 | -- The @(/\\)@ operator (or @(∧)@ U+2227) also lets you combine records, but
    |                               ^
-- The @(/\\)@ operator (or @(∧)@ U+2227) also lets you combine records, but
```

Wondering if this is a misconfiguration of the Nix tooling (i.e. should not have `-Wunicode-homoglyph` applied). The only thing in the Nix files I saw quickly was where `failOnAllWarnings` was being applied, but that might not even be related to this because that should add `-Wall` not `-Wunicode-homoglyph`.

**Comment by mattpolzin** [comment]
Well, I looked at the ticket referenced above now. Should have done that first; turns out this warning is actually part of the C preprocessor and further it seems specific to clang and maybe even certain clang versions. That means, sadly, I was unable to build `dhall-haskell` (due to being on MacOS) using any of the 3 build methods (`cabal`, `stack`, or `nix`). Cabal failed to resolve non-conflicting dependencies, Stack failed to build certain dependencies with linker errors, and Nix failed because of a warning from the clang C preprocessor. :(

**Comment by Gabriella439** [comment]
I'm more than happy to accept a PR to remove the offending character.  It's just that I can't reproduce the problem locally so I don't have an easy way to verify that any change of mine would fix it.

I'm also using `clang` (specifically, the one provided by a Nix shell), so I think it's definitely something that affects a specific version of `clang`:

```ShellSession
$ "$CC" --version
clang version 11.1.0
Target: aarch64-apple-darwin
Thread model: posix
InstalledDir: /nix/store/3zy8k5xl5s9cmcghgd90c05dga0j5h6a-clang-11.1.0/bin
```
