### ISSUE TITLE
Dhall.Core.Project should store an ordered set of field projections

### ISSUE THREAD

**Issue by ocharles** [dhall-lang/dhall-haskell#664]
Continuing from #518, which identifies that the `Set` currently used will loose field ordering.

**Comment by f-f** [comment]
@ocharles what’s the use case for this?

**Comment by MonoidMusician** [comment]
For what it’s worth, the way I’m modelling this in my dhall-purescript project is by using the same datatype used to represent records and unions, except over `()` instead of `Expr` ... (`Expr` is now parameterized over that functor too, so it can be ordered `[(String, a)]` or unordered `Map String a`, whatever.) I just think it conceptually works well to have the projection set represented in the same way as records themselves, and it seems to cost little.

**Comment by Gabriel439** [comment]
This was fixed by https://github.com/dhall-lang/dhall-haskell/pull/670
