### ISSUE TITLE
[Bug] REPL leaks memory

### ISSUE THREAD

**Issue by ari-becker** [dhall-lang/dhall-haskell#860]
Version: `1.21.0`
OS: Mac OS 10.14.3 Mojave
Compiled from source through `stack install`

Steps to reproduce:
1. Run `dhall repl`
1. Observe memory use of the `dhall` process: `2.2 MB` on my machine
1. Import an expression. Prelude works for reproduction purposes, however as it's fairly small, the impact of the memory leak is fairly small as well. To give a larger example, consider `https://raw.githubusercontent.com/coralogix/dhall-concourse/v0.3.0/default/package.dhall`. (edit: changed to v0.3.0 tag now that I've released that).
1. Observe the memory use of the `dhall` process while the expression is being evaluated: for the larger example, `812.1 MB` on my machine. I would consider this acceptable - for a large-enough expression, evaluation is going to take the amount of memory that it's going to take.
1. Allow the expression to finish evaluating and loop back to read.
1. Observe that the memory use of the `dhall` process has not returned to normal - it is still consuming `812.1 MB` of RAM
1. Import the same expression again, for the second time.
1. Observe that memory use has jumped again, now to `1.50 GB`.
1. Repeat ad-nauseum until the machine's RAM has been exhausted.

Expected behavior: unless the results of the expression have been persisted through the `:let` command, the REPL releases the memory required to evaluate the last expression after evaluation is completed.

**Comment by Gabriel439** [comment]
@ari-becker: Thanks for your patience.

So the issue here is that the `dhall repl` stores history for bound variables, even if you shadow them.  For example:

```haskell
$ result/bin/dhall repl
⊢ :let x = 2

x : Natural

⊢ :let x = 3

x : Natural

⊢ :let x = 5

x : Natural

⊢ [ x, x@1, x@2 ]

[ 5, 3, 2 ]
```

This is a language feature provided even outside the REPL: you can access shadowed variables using the `@n` notation and the above REPL session is equivalent to this Dhall expression:

```haskell
let x = 2

let x = 3

let x = 5

in  [ x, x@1, x@2 ]
```

**Comment by ari-becker** [comment]
@Gabriel439 Hi, thanks for getting to this, sorry for the slow response, I'm on vacation at the moment and don't have my work setup with me.

Assuming that you did successfully reproduce my "bug" (the "expected behavior" line of my bug report makes it sound like I was having issues even without binding through `:let`, but I can't double-check now because vacation), then I guess that the bug is in my understanding of what's going on. I don't recall reading about using `@` to access previous shadows in any of the documentation (a quick search on `Dhall.Tutorial` shows nothing) and something like that should definitely be documented.

Additionally, if this is a feature and not a bug, then shouldn't the user be given more control over the amount of memory that the REPL is using without having to quit and relaunch? Starting perhaps with something like `:reset` that releases all bindings, maybe `:reset x` which releases the `x` bindings, but I guess it also makes me wonder if this also affects tools like the language server somehow, like if there exist expressions such that shadowing would cause the language server to hold onto previous expressions and eventually consume too much memory.

On a philosophical note, I'd also ask why this kind of feature even exists. I remember that it is necessary at times to reference `_@1`, though I forget the context off the top of my head, and the way I program, if I need to reference an earlier binding then I won't shadow it; I primarily use shadowing to curry a function with common parameters so that the shadowed binding only needs the last, unique binding to provide a non-function value; doing so makes the code appear to my taste to be a little cleaner.

**Comment by Profpatsch** [comment]
> This is a language feature provided even outside the REPL: you can access shadowed variables using the `@n` notation

wat.

I don’t think this is documented somewhere, is it? I thought that’s just internals.

**Comment by Gabriel439** [comment]
@Profpatsch: The `@n` feature is not a feature of the REPL; it's a feature of the language:

```bash
$ dhall <<< 'let x = 1 let x = True in x@1'
1
```

The REPL is behaving the same way the language would.

**Comment by Gabriel439** [comment]
@Profpatsch @ari-becker: The primary motivation for the `@n` language feature is to ensure that both the user and interpreter don't have to change the variable name if they wish to preserve the name.  This comes in handy in four ways:

* α-normalization

  @ari-becker: This is probably the use case you remembered:

  ```bash
  $ dhall normalize --alpha <<< 'λ(x : Natural) → λ(y : Bool) → x'
  λ(_ : Natural) → λ(_ : Bool) → _@1
  ```

  In α-normalization, all of the variable names *must* be `_`, so the only way to distinguish them is via the `@n` syntax.  In this scenario the `@n` suffix plays the role of a De Bruijn index.

* β-normalization

  You can also run into this `@`n feature even for ordinary normalization.  For example:

  ```bash
  $ dhall <<< 'λ(x : Natural) → let y = x in λ(x : Bool) → y'
  λ(x : Natural) → λ(x : Bool) → x@1
  ```

  Here the interpreter is trying to always preserve the variable name that the user selected (`x` in this case), but in order to do so the interpreter must have a way to avoid variable capture.  The `@n` feature allows the interpreter to avoid such capture while still preserving the name the user assigned.

  @ari-becker: This is an example of how even users who did not intend to use name shadowing can still produce expressions whose normal forms have shadowed variable names.

* User preference

  Some users (like @ari-becker) might have no intention of referring to shadowed variable names, but others users might prefer to do so, perhaps because they prefer to reuse the same variable name multiple times within a large expression.

  For example, Haskell programmers do this all the time, except adding numeric suffixes (i.e. `s0`, `s1`, `s2`, etc.) or multiple `'`s to the end of their variable names (i.e. `s`, `s'`, `s''`, etc.).  The `@n` feature gives them a more systematic way of doing so that has language support.

* Ease of implementation

  The `@n` feature greatly simplifies the implementation of the language because implementations never need to generate fresh unused variable names.  The β-normalization algorithm (taken from Pierce's "Types and Programming Languages" book) is rather elegant and leads to normal forms whose variable names match the original names as closely as possible, using the minimum De Bruijn index necessary to avoid conflicts.

  Or, to put it another way, you avoid the issue that other programming languages (like PureScript) have where you have ugly inferred types like:

  ```purescript
  main :: forall t38 t39 t42 t47.
    ( MonadRec t39
    , Parallel t42 t39
    , MonadEff
        ( console :: CONSOLE
        | t47
        )
        t39
    ) => t39 t38
  ```

  The reason PureScript has these large numeric suffixes is because it's using a less elegant algorithm for avoiding name conflicts.  Dhall avoids this issue through the use of Pierce's algorithm but that algorithm requires language support for De Bruijn indices (i.e. the `@n`) and because those indices might appear in normal forms (see the second point above) they need to be made available to the user, too, not just the interpreter.

I agree that this features is missing from the documentation, and I hope to remember to fix that as part of moving the Haskell tutorial to a language-independent tutorial.

**Comment by Gabriel439** [comment]
@ari-becker: Also, I can make the scope of this issue to add REPL support for either clearing the REPL history or selectively deleting `:let` bindings from the history, like you suggested

**Comment by ari-becker** [comment]
@Gabriel439 I agree with the scope change for the issue. The @-notation sounds cool now that you've explained it, seems like an elegant way to address the issues you brought up.

**Comment by Gabriel439** [comment]
So selectively deleting a binding is possible to do, albeit tricky and error-prone (due to the need to make sure that the deletion doesn't break any other bindings), so for right now I will implement a simpler `:clear` command that deletes the entire context.
