### ISSUE TITLE
echo '[]' | dhall encode | dhall decode

### ISSUE THREAD

**Issue by singpolyma** [dhall-lang/dhall-haskell#862]
Produces the error:

```
Error: Cannot decode CBOR to Dhall

The following CBOR expression does not encode a valid Dhall expression

↳ TList [TInt 4,TNull]
```

I would expect any expression that can be encoded without error, can be decoded without error.

**Comment by Gabriel439** [comment]
@singpolyma: The real issue here is that the Haskell implementation, for parsing performance reasons, allows the expression `[]` to parse but then fail to type-check, when it should actually just fail to parse.  The change where this was made was:

https://github.com/dhall-lang/dhall-haskell/pull/606

This should be easier to fix once the standard drops support for the old-style `Optional` literal syntax because the source of the parsing slowdown was attempting to backtrack to handle the similar syntax for `List`s and `Optional`s.

**Comment by sjakobi** [comment]
We should try to fix this when implementing https://github.com/dhall-lang/dhall-lang/issues/623.

**Comment by Gabriel439** [comment]
This was fixed at some point (although I haven't dug up exactly when).  Version 1.39.0 now correctly rejects `[]` at parse time.
