### ISSUE TITLE
dhall (Haskell package version: 1.23.0) is accepting invalid code

### ISSUE THREAD

**Issue by mageshb** [dhall-lang/dhall-haskell#959]
```
let S : Type = {a : Text, b : Text} in {x = "sds", y = "Dfgfg"} : S
```
is getting accepted in dhall-1.23.0
```
⊢ let S : Type = {a : Text, b : Text} in {x = "sds", y = "Dfgfg"} : S

{ x = "sds", y = "Dfgfg" }

```

But same expression is rightly failing in dhall-1.21.0

```
⊢ let S : Type = {a : Text, b : Text} in {x = "sds", y = "Dfgfg"} : S

Error: Expression doesn't match annotation

{ - a : …
, - b : …
, + x : …
, + y : …
}

                                       {x = "sds", y = "Dfgfg"} : S
(stdin):1:40
⊢ 
Goodbye.

``` 
I guess the issue starts from dhall-1.22.0 onward.

**Comment by haitlahcen** [comment]
Good catch, this is perhaps [caused by this `toList`](https://github.com/dhall-lang/dhall-haskell/blob/7d56778350655cd9c784e05a853a37834bcae777/dhall/src/Dhall/Eval.hs#L673) which eliminate the record  field names and keep the types only. Meaning that both `{ x : Text, y : Text}` and `{ a :Text, b : Text }` are considered equal because `toList (fromList [("x", Text), ("y", Text)]) = toList (fromList [("a", Text), ("b", Text)])` ?

**Comment by Gabriel439** [comment]
Fix is up here: https://github.com/dhall-lang/dhall-haskell/pull/965
