### ISSUE TITLE
Can Dhall be used as a replacement for bash?

### ISSUE THREAD

**Issue by AnthonyJacob** [dhall-lang/dhall-haskell#97]
There is a Dhall to bash compiler. I know multiple tools that use bash as a configuration language : [herbstluft window manager](https://github.com/herbstluftwm/herbstluftwm), [kakoune text editor](https://github.com/mawww/kakoune).

Is it possible to use Dhall to generate those `config.sh` files? Do you think it is a wise idea?

**Comment by Gabriel439** [comment]
Could you clarify what you need that the existing dhall-to-bash tool doesn't do?  I'm not familiar with these configuration languages

**Comment by AnthonyJacob** [comment]
[linter config](https://github.com/mawww/kakoune/blob/b9317ba38c3e8f2bc4196705d65bbc8a8ef8dbf4/rc/base/lint.kak)

**Comment by Gabriel439** [comment]
The file you linked to is not a Bash script, though.  It looks like a kakoune-specific configuration language, similar to vimscript

**Comment by Gabriel439** [comment]
I'll close this for now because the scope of this task is not clear.  Feel free to reopen if you still have questions

**Comment by docteurklein** [comment]
The title looked pretty clear to me! Even tho the linked example was totally not a bash example.

I'm curious as well to know how much can dhall-to-bash do to reduce my necessity to write bash.
Apart from the trivial `[1, 2, 3]` examples, cause I think I can do that without dhall :)

I think that's one of the big problems with all the dhall-to-* tools out there: There is **zero** example that shows a non-trivial usage, only basic `[1, 2, 3]`! People don't have problems generating list of integers in real life (and if they do, gnu-coretools `seq 1 3` is pretty good at it).

Sorry for the rant, I'm very interested in the promise behind dhall, but for now I struggle to use it to solve real life problems.

**Comment by Gabriel439** [comment]
@docteurklein: The answer is: not too much.  `dhall-to-bash` can't run Bash commands for you and even if you try to translate "pure" Bash commands to Dhall (like `grep`/`sed`) you won't have much luck because Dhall is a very restricted language where `Text` values are opaque.

`dhall` is most commonly used to replace large and repetitive YAML files for ops-related tooling.  See:

* http://www.haskellforall.com/2019/01/dhall-year-in-review-2018-2019.html
* http://www.haskellforall.com/2019/02/dhall-survey-results-2019-2019.html

Those should give you some idea of what use cases that Dhall is focusing on.

I only implemented `dhall-to-bash` because (A) somebody asked for it and (B) it was really easy to implement, but it is not really one of the core pillars of the Dhall ecosystem.  The Dhall integrations with YAML/JSON and Ops tools like Kubernetes are the key integrations of the Dhall ecosystem and when Dhall gets Python/Go bindings then those will help as well.

**Comment by docteurklein** [comment]
thanks :)

**Comment by Gabriel439** [comment]
@docteurklein: You're welcome! 🙂

**Comment by ari-becker** [comment]
> I'm curious as well to know how much can dhall-to-bash do to reduce my necessity to write bash.
> Apart from the trivial `[1, 2, 3]` examples, cause I think I can do that without dhall :)

@docteurklein The purpose of the `dhall-to-bash` tool has more to do with rounding out the experience for people who have already transitioned most of their configuration files to Dhall. To take a simple example, let's say I have a Dhall configuration file which defines Kubernetes-related configuration, including which Kubernetes namespace is being used. So if in a bash script, you would need to write:

```bash
kubectl --namespace=<what goes here?> get pods
```

you can use the namespace by something like:

```bash
eval $(dhall-to-bash --declare kubernetes_namespace <<< '(./Config.dhall).path.to.namespace')
kubectl --namespace=${kubernetes_namespace} get pods
```

You may note that you could replace `dhall-to-bash` above with `kubernetes_namespace=$(dhall-to-text <<< '(./Config.dhall).path.to.namespace')` and the example would work almost as nicely. The `dhall-to-bash` tool mostly makes your life easier if you're extracting Optionals or Lists from a Dhall config into a Bash variable, which `dhall-to-text` doesn't know how to do on it's own.

The `dhall-to-bash` tool isn't for replacing the `kubectl get pods` bit.

Hope this helps

**Comment by PierreR** [comment]
@Gabriel439 FWIW I kind of find `dhall-to-bash` more useful than `dhall-kubernetes` so far probably because I don't quite see how `dhall-kubernetes` is useful in the context of `helm`.

On the other hand, if you wish to move out configuration out of bash scripts then in theory `dhall-to-bash` seems to make quite a lot of sense. The only issue is the lack of support for basic dhall features such union types.

I fear the problem with Yaml in the context of Ops tools is the fact that many of them are not plain Yaml anymore (Ansible, Terraform, ...) and for all of these Yaml++ DSLs there are currently no dhall bindings at all ;-)

Anyway I have just written this because I still have hope that `dhall-to-bash` fits a nice use case.

**Comment by Gabriel439** [comment]
@PierreR: Actually, now that Dhall supports empty alternatives then that allows `dhall-to-bash` to render empty alternatives as strings

**Comment by Gabriel439** [comment]
Also, I ran into another use case for `dhall-to-bash` at work recently.  We had a list of values that needed to be shared between a Haskell program and a Bash program.  I stored the list of values in a Dhall configuration file so that I could read it into Bash using `dhall-to-bash` and read it into Haskell using the `dhall` Haskell package.

**Comment by Gabriel439** [comment]
Here is the pull request to add enum support to `dhall-to-bash`: https://github.com/dhall-lang/dhall-haskell/pull/873
