### ISSUE TITLE
Formatter always escapes new lines

### ISSUE THREAD

**Issue by gamb** [dhall-lang/dhall-haskell#973]
Is this expected?
```
gamble@nixos> cat some.dhall
{ body = ''

one

two

three

'' }

gamble@nixos> cat some.dhall | dhall format
{ body = "\none\n\ntwo\n\nthree\n\n" }

gamble@nixos> dhall version
Haskell package version: 1.23.0
Standard version: none
```
I can workaround as follows:
```
gamble@nixos> cat some.dhall 
{ body = ./multiline.dhall }
gamble@nixos> cat multiline.dhall | dhall format
''

one

two

three

''
```

**Comment by gamb** [comment]
I found that newlines are preserved in this case:
```
gamble@nixos> cat some.dhall 
{ body = ./multiline.dhall }
gamble@nixos> cat multiline.dhall | dhall format
''

one

two

three

''
```
So that'll do :)

**Comment by Gabriel439** [comment]
@gamb: Sort of.  The formatter currently uses the double-quoted form if it fits on one line, but that could be changed.

However, it is weird that moving the multi-line string into a separate file changes the behavior.  I'm pretty sure that such a difference is a bug no matter what the desired behavior is in the end.

**Comment by Gabriel439** [comment]
@gamb: So the good news is that I found the source of the inconsistency and know how to fix it.  The bad news is that fixing it makes both versions render on one line :slightly_smiling_face: (which was actually the intended behavior from the beginning).  Are you sure that you want me to fix this?

**Comment by gamb** [comment]
@Gabriel439 Haha thanks for checking this out :slightly_smiling_face:. If the formatter sees a `''` block, my feeling is that it shouldn't replace with a one-line `"`, irrespective of line length.

**Comment by Gabriel439** [comment]
@gamb: The issue is that Dhall's `prettyprinter` dependency requires expressions to support a newline-free form if you request them to attempt a compact representation.

This was the source of the inconsistency because we attempt to render records in a compact format if possible (i.e. `{ x = 1, y = 2 }` on a single line), but that in turn requires also attempting to render their substituent expressions compactly, too.  If multi-line strings didn't support a compact single-line representation then the prettyprinter would fail attempting to do so.

The reason why naked multi-line string literals were not rendered compactly was because there was no top-level attempt to render expressions compactly.

So as far as I can tell the the three options we have are:

* Do nothing (i.e. keep the current behavior)
* Consistently render multi-line strings compactly if they fit on one line
* Provide a global flag to disable compact representations for the entire expression

... but I don't think we can selectively disable the compact representation for multi-line string literals and nothing else.

**Comment by gamb** [comment]
@Gabriel439 Thanks for explaining. My two cents is that opinionated formatting _is_ a good thing (e.g. `gofmt`, `refmt` avoid configuration flags).

I found the compact behaviour confusing at first, but consistent application (option 2) seems preferable to me.

**Comment by gamb** [comment]
Semi-related, I think my original requirement would have been better served by a `readFile` builtin a bit like Nix:

```dhall
{ body = readFile "./some.markdown" }
```

**Comment by f-f** [comment]
@gamb 

the Dhall equivalent of that is

```dhall
{ body = ./some.markdown as Text }
```

**Comment by gamb** [comment]
@f-f Oh wow! Thanks :)

**Comment by f-f** [comment]
You're welcome 🙂
